/* Generated by Cython 0.9.6.14 on Mon Nov 17 17:50:03 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static char * __pyx_cfilenm= __FILE__;
static char *__pyx_filename;
static char **__pyx_f;

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static int __Pyx_CheckKeywordStrings(PyObject *kwdict, const char* function_name, int kw_allowed); /*proto*/

static INLINE int __Pyx_SplitStarArg(PyObject **args, Py_ssize_t nargs, PyObject **args2); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static inline PyObject* __Pyx_PyObject_Append(PyObject* L, PyObject* x) {
    if (likely(PyList_CheckExact(L))) {
        if (PyList_Append(L, x) < 0) return NULL;
        Py_INCREF(Py_None);
        return Py_None; // this is just to have an accurate signature
    }
    else {
        return PyObject_CallMethod(L, "append", "(O)", x);
    }
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/

static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations */

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":19
 * #    along with Tichy.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * cdef struct c_Vect:             # <<<<<<<<<<<<<< 
 *     int x
 *     int y
 */

struct __pyx_t_3geo_c_Vect {
  int x;
  int y;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":29
 * cdef inline int c_vect_equal(c_Vect* v1, c_Vect* v2)
 * 
 * cdef struct c_Rect:             # <<<<<<<<<<<<<< 
 *     c_Vect pos
 *     c_Vect size
 */

struct __pyx_t_3geo_c_Rect {
  struct __pyx_t_3geo_c_Vect pos;
  struct __pyx_t_3geo_c_Vect size;
};

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pxd":22
 * from geo cimport Vect
 * 
 * cdef class Object:             # <<<<<<<<<<<<<< 
 *     cdef void _emit(self, char* event) except *
 *     cdef void _emit_1(self, char* event, v) except *
 */

struct __pyx_obj_7cobject_Object {
  PyObject_HEAD
  struct __pyx_vtabstruct_7cobject_Object *__pyx_vtab;
  PyObject *__listeners;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":33
 *     c_Vect size
 * 
 * cdef class Rect:             # <<<<<<<<<<<<<< 
 *     cdef c_Rect c_value
 *     
 */

struct __pyx_obj_3geo_Rect {
  PyObject_HEAD
  struct __pyx_vtabstruct_3geo_Rect *__pyx_vtab;
  struct __pyx_t_3geo_c_Rect c_value;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":23
 *     int y
 * 
 * cdef class Vect:             # <<<<<<<<<<<<<< 
 *     cdef c_Vect c_value
 *     
 */

struct __pyx_obj_3geo_Vect {
  PyObject_HEAD
  struct __pyx_t_3geo_c_Vect c_value;
};


/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":22
 * from tichy.tasklet import Tasklet
 * 
 * cdef class Object:             # <<<<<<<<<<<<<< 
 *     """This class implements the observer patern
 *     
 */

struct __pyx_vtabstruct_7cobject_Object {
  void (*_emit)(struct __pyx_obj_7cobject_Object *, char *);
  void (*_emit_1)(struct __pyx_obj_7cobject_Object *, char *, PyObject *);
};
static struct __pyx_vtabstruct_7cobject_Object *__pyx_vtabptr_7cobject_Object;


/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":33
 *     c_Vect size
 * 
 * cdef class Rect:             # <<<<<<<<<<<<<< 
 *     cdef c_Rect c_value
 *     
 */

struct __pyx_vtabstruct_3geo_Rect {
  struct __pyx_obj_3geo_Rect *(*move)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Vect *);
  struct __pyx_obj_3geo_Rect *(*clip)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  struct __pyx_obj_3geo_Rect *(*merge)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  int (*intersect)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  struct __pyx_obj_3geo_Rect *(*inside)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
};
static struct __pyx_vtabstruct_3geo_Rect *__pyx_vtabptr_3geo_Rect;

static PyTypeObject *__pyx_ptype_3geo_Vect = 0;
static PyTypeObject *__pyx_ptype_3geo_Rect = 0;
static struct __pyx_obj_3geo_Vect *(*__pyx_f_3geo_c_vect_to_py)(struct __pyx_t_3geo_c_Vect *); /*proto*/
static int (*__pyx_f_3geo_c_vect_equal)(struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Vect *); /*proto*/
static struct __pyx_obj_3geo_Rect *(*__pyx_f_3geo_c_rect_to_py)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_left)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_right)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_top)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_bottom)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_width)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_height)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_contains)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_intersect)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_inside)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_merge)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_clip)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_move)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Rect *); /*proto*/

static PyTypeObject *__pyx_ptype_7cobject_Object = 0;


/* Implementation of cobject */

static char __pyx_k_3[] = "tichy.tasklet";

static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_connect;
static PyObject *__pyx_n_connect_object;
static PyObject *__pyx_n_disconnect;
static PyObject *__pyx_n_emit;
static PyObject *__pyx_n_monitor;
static PyObject *__pyx_n_types;
static PyObject *__pyx_n_GeneratorType;
static PyObject *__pyx_n_Tasklet;

static PyObject *__pyx_k_3p;

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":28
 *         But i think gobject may be overkill there... still thinking about it...
 *     """
 *     def __init__(self):             # <<<<<<<<<<<<<< 
 *         self.__listeners = {}
 *         
 */

static int __pyx_pf_7cobject_6Object___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_7cobject_6Object___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  if (unlikely(PyTuple_GET_SIZE(__pyx_args) > 0)) {
    __Pyx_RaiseArgtupleTooLong(0, PyTuple_GET_SIZE(__pyx_args));
    return -1;
  }
  if (unlikely(__pyx_kwds)) {
    if (unlikely(!__Pyx_CheckKeywordStrings(__pyx_kwds, "__init__", 0))) return -1;
  }
  __pyx_1 = PyDict_New(); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":29
 *     """
 *     def __init__(self):
 *         self.__listeners = {}             # <<<<<<<<<<<<<< 
 *         
 *     def connect(self, char* event, callback, *args):
 */
  Py_DECREF(((PyObject *)((struct __pyx_obj_7cobject_Object *)__pyx_v_self)->__listeners));
  ((struct __pyx_obj_7cobject_Object *)__pyx_v_self)->__listeners = __pyx_1;
  __pyx_1 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("cobject.Object.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":31
 *         self.__listeners = {}
 *         
 *     def connect(self, char* event, callback, *args):             # <<<<<<<<<<<<<< 
 *         """Connect the object to a given event""" 
 *         return self.connect_object(event, callback, self, *args)
 */

static PyObject *__pyx_pf_7cobject_6Object_connect(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7cobject_6Object_connect[] = "Connect the object to a given event";
static PyObject *__pyx_pf_7cobject_6Object_connect(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_event;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_v_args = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"event","callback",0};
  if (likely(PyTuple_GET_SIZE(__pyx_args) <= 2)) {
    Py_INCREF(__pyx_args);
    __pyx_v_args = __pyx_empty_tuple; Py_INCREF(__pyx_empty_tuple);
  }
  else {
    if (unlikely(__Pyx_SplitStarArg(&__pyx_args, 2, &__pyx_v_args) < 0)) return NULL;
  }
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_event = PyString_AsString(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely((!__pyx_v_event) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L2;}
    __pyx_v_callback = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "sO", __pyx_argnames, &__pyx_v_event, &__pyx_v_callback))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_DECREF(__pyx_args);
  Py_DECREF(__pyx_v_args);
  __Pyx_AddTraceback("cobject.Object.connect");
  return NULL;
  __pyx_L3:;

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":33
 *     def connect(self, char* event, callback, *args):
 *         """Connect the object to a given event""" 
 *         return self.connect_object(event, callback, self, *args)             # <<<<<<<<<<<<<< 
 *         
 *     def connect_object(self, char* event, callback, obj, *args):
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_connect_object); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_event); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(3); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  Py_INCREF(__pyx_v_callback);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_callback);
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_v_self);
  __pyx_2 = 0;
  __pyx_2 = PySequence_Tuple(__pyx_v_args); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyNumber_Add(((PyObject *)__pyx_3), __pyx_2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_3 = PyObject_Call(__pyx_1, __pyx_4, NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cobject.Object.connect");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_args);
  Py_DECREF(__pyx_args);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":35
 *         return self.connect_object(event, callback, self, *args)
 *         
 *     def connect_object(self, char* event, callback, obj, *args):             # <<<<<<<<<<<<<< 
 *         """Connect an event using a given object instead of self"""
 *         connection = (callback, obj, args)
 */

static PyObject *__pyx_n_setdefault;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_id;

static PyObject *__pyx_builtin_id;

static PyObject *__pyx_pf_7cobject_6Object_connect_object(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7cobject_6Object_connect_object[] = "Connect an event using a given object instead of self";
static PyObject *__pyx_pf_7cobject_6Object_connect_object(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_event;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_v_obj = 0;
  PyObject *__pyx_v_args = 0;
  PyObject *__pyx_v_connection;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"event","callback","obj",0};
  if (likely(PyTuple_GET_SIZE(__pyx_args) <= 3)) {
    Py_INCREF(__pyx_args);
    __pyx_v_args = __pyx_empty_tuple; Py_INCREF(__pyx_empty_tuple);
  }
  else {
    if (unlikely(__Pyx_SplitStarArg(&__pyx_args, 3, &__pyx_v_args) < 0)) return NULL;
  }
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 3)) {
    __pyx_v_event = PyString_AsString(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely((!__pyx_v_event) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L2;}
    __pyx_v_callback = PyTuple_GET_ITEM(__pyx_args, 1);
    __pyx_v_obj = PyTuple_GET_ITEM(__pyx_args, 2);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "sOO", __pyx_argnames, &__pyx_v_event, &__pyx_v_callback, &__pyx_v_obj))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_DECREF(__pyx_args);
  Py_DECREF(__pyx_v_args);
  __Pyx_AddTraceback("cobject.Object.connect_object");
  return NULL;
  __pyx_L3:;
  __pyx_v_connection = Py_None; Py_INCREF(Py_None);

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":37
 *     def connect_object(self, char* event, callback, obj, *args):
 *         """Connect an event using a given object instead of self"""
 *         connection = (callback, obj, args)             # <<<<<<<<<<<<<< 
 *         self.__listeners.setdefault(event, []).append(connection)
 *         return id(connection)
 */
  __pyx_1 = PyTuple_New(3); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_callback);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_callback);
  Py_INCREF(__pyx_v_obj);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_obj);
  Py_INCREF(__pyx_v_args);
  PyTuple_SET_ITEM(__pyx_1, 2, __pyx_v_args);
  Py_DECREF(__pyx_v_connection);
  __pyx_v_connection = ((PyObject *)__pyx_1);
  __pyx_1 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":38
 *         """Connect an event using a given object instead of self"""
 *         connection = (callback, obj, args)
 *         self.__listeners.setdefault(event, []).append(connection)             # <<<<<<<<<<<<<< 
 *         return id(connection)
 *         
 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_7cobject_Object *)__pyx_v_self)->__listeners), __pyx_n_setdefault); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_event); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyList_New(0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, ((PyObject *)__pyx_3));
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  __pyx_3 = __Pyx_PyObject_Append(__pyx_2, __pyx_v_connection); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":39
 *         connection = (callback, obj, args)
 *         self.__listeners.setdefault(event, []).append(connection)
 *         return id(connection)             # <<<<<<<<<<<<<< 
 *         
 *     def disconnect(self, oid):
 */
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_connection);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_connection);
  __pyx_4 = PyObject_Call(__pyx_builtin_id, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cobject.Object.connect_object");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_connection);
  Py_DECREF(__pyx_args);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":41
 *         return id(connection)
 *         
 *     def disconnect(self, oid):             # <<<<<<<<<<<<<< 
 *         """remove a connection from the listeners"""
 *         for l in self.__listeners.itervalues():
 */

static PyObject *__pyx_n_itervalues;
static PyObject *__pyx_n_remove;
static PyObject *__pyx_n_Exception;

static PyObject *__pyx_k_5p;

static PyObject *__pyx_builtin_Exception;

static char __pyx_k_5[] = "trying to disconnect a bad id";

static PyObject *__pyx_pf_7cobject_6Object_disconnect(PyObject *__pyx_v_self, PyObject *__pyx_v_oid); /*proto*/
static char __pyx_doc_7cobject_6Object_disconnect[] = "remove a connection from the listeners";
static PyObject *__pyx_pf_7cobject_6Object_disconnect(PyObject *__pyx_v_self, PyObject *__pyx_v_oid) {
  PyObject *__pyx_v_l;
  PyObject *__pyx_v_c;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_ssize_t __pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  int __pyx_7;
  PyObject *__pyx_8 = 0;
  __pyx_v_l = Py_None; Py_INCREF(Py_None);
  __pyx_v_c = Py_None; Py_INCREF(Py_None);

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":43
 *     def disconnect(self, oid):
 *         """remove a connection from the listeners"""
 *         for l in self.__listeners.itervalues():             # <<<<<<<<<<<<<< 
 *             for c in l:
 *                 if id(c) == oid:
 */
  __pyx_2 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_7cobject_Object *)__pyx_v_self)->__listeners), __pyx_n_itervalues); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyList_CheckExact(__pyx_3)) { __pyx_1 = 0; __pyx_2 = __pyx_3; Py_INCREF(__pyx_2); }
  else { __pyx_2 = PyObject_GetIter(__pyx_3); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1;} }
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    if (PyList_CheckExact(__pyx_2)) { if (__pyx_1 >= PyList_GET_SIZE(__pyx_2)) break; __pyx_3 = PyList_GET_ITEM(__pyx_2, __pyx_1++); Py_INCREF(__pyx_3); }
    else {
      __pyx_3 = PyIter_Next(__pyx_2);
      if (!__pyx_3) {
        break;
      }
    }
    Py_DECREF(__pyx_v_l);
    __pyx_v_l = __pyx_3;
    __pyx_3 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":44
 *         """remove a connection from the listeners"""
 *         for l in self.__listeners.itervalues():
 *             for c in l:             # <<<<<<<<<<<<<< 
 *                 if id(c) == oid:
 *                     l.remove(c)
 */
    if (PyList_CheckExact(__pyx_v_l)) { __pyx_4 = 0; __pyx_3 = __pyx_v_l; Py_INCREF(__pyx_3); }
    else { __pyx_3 = PyObject_GetIter(__pyx_v_l); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1;} }
    for (;;) {
      if (PyList_CheckExact(__pyx_3)) { if (__pyx_4 >= PyList_GET_SIZE(__pyx_3)) break; __pyx_5 = PyList_GET_ITEM(__pyx_3, __pyx_4++); Py_INCREF(__pyx_5); }
      else {
        __pyx_5 = PyIter_Next(__pyx_3);
        if (!__pyx_5) {
          break;
        }
      }
      Py_DECREF(__pyx_v_c);
      __pyx_v_c = __pyx_5;
      __pyx_5 = 0;

      /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":45
 *         for l in self.__listeners.itervalues():
 *             for c in l:
 *                 if id(c) == oid:             # <<<<<<<<<<<<<< 
 *                     l.remove(c)
 *                     return
 */
      __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_INCREF(__pyx_v_c);
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_c);
      __pyx_6 = PyObject_Call(__pyx_builtin_id, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
      __pyx_5 = PyObject_RichCompare(__pyx_6, __pyx_v_oid, Py_EQ); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      __pyx_7 = __Pyx_PyObject_IsTrue(__pyx_5); if (unlikely(__pyx_7 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      if (__pyx_7) {

        /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":46
 *             for c in l:
 *                 if id(c) == oid:
 *                     l.remove(c)             # <<<<<<<<<<<<<< 
 *                     return
 *         raise Exception("trying to disconnect a bad id")
 */
        __pyx_6 = PyObject_GetAttr(__pyx_v_l, __pyx_n_remove); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1;}
        __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_INCREF(__pyx_v_c);
        PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_c);
        __pyx_8 = PyObject_Call(__pyx_6, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_8)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
        Py_DECREF(__pyx_8); __pyx_8 = 0;

        /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":47
 *                 if id(c) == oid:
 *                     l.remove(c)
 *                     return             # <<<<<<<<<<<<<< 
 *         raise Exception("trying to disconnect a bad id")
 *         
 */
        __pyx_r = Py_None; Py_INCREF(Py_None);
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        goto __pyx_L0;
        goto __pyx_L8;
      }
      __pyx_L8:;
    }
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":48
 *                     l.remove(c)
 *                     return
 *         raise Exception("trying to disconnect a bad id")             # <<<<<<<<<<<<<< 
 *         
 *     def emit(self, char* event, *args):
 */
  __pyx_6 = PyTuple_New(1); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_k_5p);
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_k_5p);
  __pyx_5 = PyObject_Call(__pyx_builtin_Exception, ((PyObject *)__pyx_6), NULL); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_6)); __pyx_6 = 0;
  __Pyx_Raise(__pyx_5, 0, 0);
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("cobject.Object.disconnect");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_l);
  Py_DECREF(__pyx_v_c);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":50
 *         raise Exception("trying to disconnect a bad id")
 *         
 *     def emit(self, char* event, *args):             # <<<<<<<<<<<<<< 
 *         """Emit a signal
 *         
 */

static PyObject *__pyx_n_get;
static PyObject *__pyx_n_generator;
static PyObject *__pyx_n_start;


static PyObject *__pyx_pf_7cobject_6Object_emit(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7cobject_6Object_emit[] = "Emit a signal\n        \n           All the listeners will be notified\n        ";
static PyObject *__pyx_pf_7cobject_6Object_emit(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_event;
  PyObject *__pyx_v_args = 0;
  PyObject *__pyx_v_e;
  PyObject *__pyx_v_eargs;
  PyObject *__pyx_v_call;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  int __pyx_7;
  static char *__pyx_argnames[] = {"event",0};
  if (likely(PyTuple_GET_SIZE(__pyx_args) <= 1)) {
    Py_INCREF(__pyx_args);
    __pyx_v_args = __pyx_empty_tuple; Py_INCREF(__pyx_empty_tuple);
  }
  else {
    if (unlikely(__Pyx_SplitStarArg(&__pyx_args, 1, &__pyx_v_args) < 0)) return NULL;
  }
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 1)) {
    __pyx_v_event = PyString_AsString(PyTuple_GET_ITEM(__pyx_args, 0)); if (unlikely((!__pyx_v_event) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s", __pyx_argnames, &__pyx_v_event))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_DECREF(__pyx_args);
  Py_DECREF(__pyx_v_args);
  __Pyx_AddTraceback("cobject.Object.emit");
  return NULL;
  __pyx_L3:;
  __pyx_v_e = Py_None; Py_INCREF(Py_None);
  __pyx_v_eargs = Py_None; Py_INCREF(Py_None);
  __pyx_v_call = Py_None; Py_INCREF(Py_None);

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":55
 *            All the listeners will be notified
 *         """
 *         for e in self.__listeners.get(event, []):             # <<<<<<<<<<<<<< 
 *             eargs = args + e[2]
 *             call = e[0](e[1], *eargs)
 */
  __pyx_2 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_7cobject_Object *)__pyx_v_self)->__listeners), __pyx_n_get); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyString_FromString(__pyx_v_event); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyList_New(0); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 1, ((PyObject *)__pyx_4));
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
  if (PyList_CheckExact(__pyx_3)) { __pyx_1 = 0; __pyx_4 = __pyx_3; Py_INCREF(__pyx_4); }
  else { __pyx_4 = PyObject_GetIter(__pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1;} }
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    if (PyList_CheckExact(__pyx_4)) { if (__pyx_1 >= PyList_GET_SIZE(__pyx_4)) break; __pyx_2 = PyList_GET_ITEM(__pyx_4, __pyx_1++); Py_INCREF(__pyx_2); }
    else {
      __pyx_2 = PyIter_Next(__pyx_4);
      if (!__pyx_2) {
        break;
      }
    }
    Py_DECREF(__pyx_v_e);
    __pyx_v_e = __pyx_2;
    __pyx_2 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":56
 *         """
 *         for e in self.__listeners.get(event, []):
 *             eargs = args + e[2]             # <<<<<<<<<<<<<< 
 *             call = e[0](e[1], *eargs)
 *             # Now in case the callback is a generator, we turn it into a task
 */
    if (PyList_CheckExact(__pyx_v_e) && 0 <= 2 && 2 < PyList_GET_SIZE(__pyx_v_e)) {
      __pyx_3 = PyList_GET_ITEM(__pyx_v_e, 2); Py_INCREF(__pyx_3);
      } else if (PyTuple_CheckExact(__pyx_v_e) && 0 <= 2 && 2 < PyTuple_GET_SIZE(__pyx_v_e)) {
      __pyx_3 = PyTuple_GET_ITEM(__pyx_v_e, 2); Py_INCREF(__pyx_3);
      } else {
      __pyx_5 = PyInt_FromLong(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_3 = PyObject_GetItem(__pyx_v_e, __pyx_5); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }
    __pyx_2 = PyNumber_Add(__pyx_v_args, __pyx_3); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_eargs);
    __pyx_v_eargs = __pyx_2;
    __pyx_2 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":57
 *         for e in self.__listeners.get(event, []):
 *             eargs = args + e[2]
 *             call = e[0](e[1], *eargs)             # <<<<<<<<<<<<<< 
 *             # Now in case the callback is a generator, we turn it into a task
 *             # This allow us to directly connect to generators
 */
    if (PyList_CheckExact(__pyx_v_e) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_e)) {
      __pyx_3 = PyList_GET_ITEM(__pyx_v_e, 0); Py_INCREF(__pyx_3);
      } else if (PyTuple_CheckExact(__pyx_v_e) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_e)) {
      __pyx_3 = PyTuple_GET_ITEM(__pyx_v_e, 0); Py_INCREF(__pyx_3);
      } else {
      __pyx_5 = PyInt_FromLong(0); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_3 = PyObject_GetItem(__pyx_v_e, __pyx_5); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }
    if (PyList_CheckExact(__pyx_v_e) && 0 <= 1 && 1 < PyList_GET_SIZE(__pyx_v_e)) {
      __pyx_5 = PyList_GET_ITEM(__pyx_v_e, 1); Py_INCREF(__pyx_5);
      } else if (PyTuple_CheckExact(__pyx_v_e) && 0 <= 1 && 1 < PyTuple_GET_SIZE(__pyx_v_e)) {
      __pyx_5 = PyTuple_GET_ITEM(__pyx_v_e, 1); Py_INCREF(__pyx_5);
      } else {
      __pyx_2 = PyInt_FromLong(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_5 = PyObject_GetItem(__pyx_v_e, __pyx_2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
    }
    __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_5 = PySequence_Tuple(__pyx_v_eargs); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_6 = PyNumber_Add(((PyObject *)__pyx_2), __pyx_5); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_2 = PyObject_Call(__pyx_3, __pyx_6, NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_v_call);
    __pyx_v_call = __pyx_2;
    __pyx_2 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":60
 *             # Now in case the callback is a generator, we turn it into a task
 *             # This allow us to directly connect to generators
 *             if type(call) is GeneratorType:             # <<<<<<<<<<<<<< 
 *                 Tasklet(generator=call).start()
 *         
 */
    __pyx_5 = PyTuple_New(1); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_INCREF(__pyx_v_call);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_call);
    __pyx_3 = PyObject_Call(((PyObject*)&PyType_Type), ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
    __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_GeneratorType); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_7 = (__pyx_3 == __pyx_6);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    if (__pyx_7) {

      /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":61
 *             # This allow us to directly connect to generators
 *             if type(call) is GeneratorType:
 *                 Tasklet(generator=call).start()             # <<<<<<<<<<<<<< 
 *         
 *     cdef void _emit(self, char* event) except *:
 */
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Tasklet); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_5 = PyDict_New(); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
      if (PyDict_SetItem(__pyx_5, __pyx_n_generator, __pyx_v_call) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_3 = PyEval_CallObjectWithKeywords(__pyx_2, ((PyObject *)__pyx_empty_tuple), ((PyObject *)__pyx_5)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
      __pyx_6 = PyObject_GetAttr(__pyx_3, __pyx_n_start); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_2 = PyObject_Call(__pyx_6, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      goto __pyx_L6;
    }
    __pyx_L6:;
  }
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("cobject.Object.emit");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_eargs);
  Py_DECREF(__pyx_v_call);
  Py_DECREF(__pyx_args);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":63
 *                 Tasklet(generator=call).start()
 *         
 *     cdef void _emit(self, char* event) except *:             # <<<<<<<<<<<<<< 
 *         """An optimized version of emit only for internal use"""
 *         for e in self.__listeners.get(event, []):
 */

static  void __pyx_f_7cobject_6Object__emit(struct __pyx_obj_7cobject_Object *__pyx_v_self, char *__pyx_v_event) {
  PyObject *__pyx_v_e;
  Py_ssize_t __pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  __pyx_v_e = Py_None; Py_INCREF(Py_None);

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":65
 *     cdef void _emit(self, char* event) except *:
 *         """An optimized version of emit only for internal use"""
 *         for e in self.__listeners.get(event, []):             # <<<<<<<<<<<<<< 
 *             e[0](e[1], *e[2])
 *             
 */
  __pyx_2 = PyObject_GetAttr(((PyObject *)__pyx_v_self->__listeners), __pyx_n_get); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyString_FromString(__pyx_v_event); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyList_New(0); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 1, ((PyObject *)__pyx_4));
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
  if (PyList_CheckExact(__pyx_3)) { __pyx_1 = 0; __pyx_4 = __pyx_3; Py_INCREF(__pyx_4); }
  else { __pyx_4 = PyObject_GetIter(__pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;} }
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    if (PyList_CheckExact(__pyx_4)) { if (__pyx_1 >= PyList_GET_SIZE(__pyx_4)) break; __pyx_2 = PyList_GET_ITEM(__pyx_4, __pyx_1++); Py_INCREF(__pyx_2); }
    else {
      __pyx_2 = PyIter_Next(__pyx_4);
      if (!__pyx_2) {
        break;
      }
    }
    Py_DECREF(__pyx_v_e);
    __pyx_v_e = __pyx_2;
    __pyx_2 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":66
 *         """An optimized version of emit only for internal use"""
 *         for e in self.__listeners.get(event, []):
 *             e[0](e[1], *e[2])             # <<<<<<<<<<<<<< 
 *             
 *     cdef void _emit_1(self, char* event, a) except *:
 */
    if (PyList_CheckExact(__pyx_v_e) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_e)) {
      __pyx_3 = PyList_GET_ITEM(__pyx_v_e, 0); Py_INCREF(__pyx_3);
      } else if (PyTuple_CheckExact(__pyx_v_e) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_e)) {
      __pyx_3 = PyTuple_GET_ITEM(__pyx_v_e, 0); Py_INCREF(__pyx_3);
      } else {
      __pyx_5 = PyInt_FromLong(0); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_3 = PyObject_GetItem(__pyx_v_e, __pyx_5); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }
    if (PyList_CheckExact(__pyx_v_e) && 0 <= 1 && 1 < PyList_GET_SIZE(__pyx_v_e)) {
      __pyx_5 = PyList_GET_ITEM(__pyx_v_e, 1); Py_INCREF(__pyx_5);
      } else if (PyTuple_CheckExact(__pyx_v_e) && 0 <= 1 && 1 < PyTuple_GET_SIZE(__pyx_v_e)) {
      __pyx_5 = PyTuple_GET_ITEM(__pyx_v_e, 1); Py_INCREF(__pyx_5);
      } else {
      __pyx_2 = PyInt_FromLong(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_5 = PyObject_GetItem(__pyx_v_e, __pyx_2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
    }
    __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_5);
    __pyx_5 = 0;
    if (PyList_CheckExact(__pyx_v_e) && 0 <= 2 && 2 < PyList_GET_SIZE(__pyx_v_e)) {
      __pyx_6 = PyList_GET_ITEM(__pyx_v_e, 2); Py_INCREF(__pyx_6);
      } else if (PyTuple_CheckExact(__pyx_v_e) && 0 <= 2 && 2 < PyTuple_GET_SIZE(__pyx_v_e)) {
      __pyx_6 = PyTuple_GET_ITEM(__pyx_v_e, 2); Py_INCREF(__pyx_6);
      } else {
      __pyx_5 = PyInt_FromLong(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_6 = PyObject_GetItem(__pyx_v_e, __pyx_5); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }
    __pyx_5 = PySequence_Tuple(__pyx_6); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_6 = PyNumber_Add(((PyObject *)__pyx_2), __pyx_5); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_2 = PyObject_Call(__pyx_3, __pyx_6, NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("cobject.Object._emit");
  __pyx_L0:;
  Py_DECREF(__pyx_v_e);
}

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":68
 *             e[0](e[1], *e[2])
 *             
 *     cdef void _emit_1(self, char* event, a) except *:             # <<<<<<<<<<<<<< 
 *         """An optimized version of emit only for internal use"""
 *         for e in self.__listeners.get(event, []):
 */

static  void __pyx_f_7cobject_6Object__emit_1(struct __pyx_obj_7cobject_Object *__pyx_v_self, char *__pyx_v_event, PyObject *__pyx_v_a) {
  PyObject *__pyx_v_e;
  Py_ssize_t __pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  __pyx_v_e = Py_None; Py_INCREF(Py_None);

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":70
 *     cdef void _emit_1(self, char* event, a) except *:
 *         """An optimized version of emit only for internal use"""
 *         for e in self.__listeners.get(event, []):             # <<<<<<<<<<<<<< 
 *             e[0](e[1], a, *e[2])
 * 
 */
  __pyx_2 = PyObject_GetAttr(((PyObject *)__pyx_v_self->__listeners), __pyx_n_get); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyString_FromString(__pyx_v_event); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyList_New(0); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 1, ((PyObject *)__pyx_4));
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_5), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_5)); __pyx_5 = 0;
  if (PyList_CheckExact(__pyx_3)) { __pyx_1 = 0; __pyx_4 = __pyx_3; Py_INCREF(__pyx_4); }
  else { __pyx_4 = PyObject_GetIter(__pyx_3); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1;} }
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    if (PyList_CheckExact(__pyx_4)) { if (__pyx_1 >= PyList_GET_SIZE(__pyx_4)) break; __pyx_2 = PyList_GET_ITEM(__pyx_4, __pyx_1++); Py_INCREF(__pyx_2); }
    else {
      __pyx_2 = PyIter_Next(__pyx_4);
      if (!__pyx_2) {
        break;
      }
    }
    Py_DECREF(__pyx_v_e);
    __pyx_v_e = __pyx_2;
    __pyx_2 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":71
 *         """An optimized version of emit only for internal use"""
 *         for e in self.__listeners.get(event, []):
 *             e[0](e[1], a, *e[2])             # <<<<<<<<<<<<<< 
 * 
 *     def monitor(self, object, char* event, callback, *args):
 */
    if (PyList_CheckExact(__pyx_v_e) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_e)) {
      __pyx_3 = PyList_GET_ITEM(__pyx_v_e, 0); Py_INCREF(__pyx_3);
      } else if (PyTuple_CheckExact(__pyx_v_e) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_e)) {
      __pyx_3 = PyTuple_GET_ITEM(__pyx_v_e, 0); Py_INCREF(__pyx_3);
      } else {
      __pyx_5 = PyInt_FromLong(0); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_3 = PyObject_GetItem(__pyx_v_e, __pyx_5); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }
    if (PyList_CheckExact(__pyx_v_e) && 0 <= 1 && 1 < PyList_GET_SIZE(__pyx_v_e)) {
      __pyx_5 = PyList_GET_ITEM(__pyx_v_e, 1); Py_INCREF(__pyx_5);
      } else if (PyTuple_CheckExact(__pyx_v_e) && 0 <= 1 && 1 < PyTuple_GET_SIZE(__pyx_v_e)) {
      __pyx_5 = PyTuple_GET_ITEM(__pyx_v_e, 1); Py_INCREF(__pyx_5);
      } else {
      __pyx_2 = PyInt_FromLong(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_5 = PyObject_GetItem(__pyx_v_e, __pyx_2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
    }
    __pyx_2 = PyTuple_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_5);
    Py_INCREF(__pyx_v_a);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_a);
    __pyx_5 = 0;
    if (PyList_CheckExact(__pyx_v_e) && 0 <= 2 && 2 < PyList_GET_SIZE(__pyx_v_e)) {
      __pyx_6 = PyList_GET_ITEM(__pyx_v_e, 2); Py_INCREF(__pyx_6);
      } else if (PyTuple_CheckExact(__pyx_v_e) && 0 <= 2 && 2 < PyTuple_GET_SIZE(__pyx_v_e)) {
      __pyx_6 = PyTuple_GET_ITEM(__pyx_v_e, 2); Py_INCREF(__pyx_6);
      } else {
      __pyx_5 = PyInt_FromLong(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_6 = PyObject_GetItem(__pyx_v_e, __pyx_5); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }
    __pyx_5 = PySequence_Tuple(__pyx_6); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_6 = PyNumber_Add(((PyObject *)__pyx_2), __pyx_5); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_2 = PyObject_Call(__pyx_3, __pyx_6, NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("cobject.Object._emit_1");
  __pyx_L0:;
  Py_DECREF(__pyx_v_e);
}

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":73
 *             e[0](e[1], a, *e[2])
 * 
 *     def monitor(self, object, char* event, callback, *args):             # <<<<<<<<<<<<<< 
 *         """connect an object to a callback, and automatically disconnect it
 *         when this object is destroyed.
 */

static PyObject *__pyx_n_destroyed;
static PyObject *__pyx_n__on_monitor_destroyed;


static PyObject *__pyx_pf_7cobject_6Object_monitor(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_7cobject_6Object_monitor[] = "connect an object to a callback, and automatically disconnect it\n        when this object is destroyed.\n\n        WARNING: This is still experimental, and should only be used\n        with objects that have a \'destroy\' signal.\n        ";
static PyObject *__pyx_pf_7cobject_6Object_monitor(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_object = 0;
  char *__pyx_v_event;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_v_args = 0;
  PyObject *__pyx_v_connection;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"object","event","callback",0};
  if (likely(PyTuple_GET_SIZE(__pyx_args) <= 3)) {
    Py_INCREF(__pyx_args);
    __pyx_v_args = __pyx_empty_tuple; Py_INCREF(__pyx_empty_tuple);
  }
  else {
    if (unlikely(__Pyx_SplitStarArg(&__pyx_args, 3, &__pyx_v_args) < 0)) return NULL;
  }
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 3)) {
    __pyx_v_object = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_event = PyString_AsString(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((!__pyx_v_event) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L2;}
    __pyx_v_callback = PyTuple_GET_ITEM(__pyx_args, 2);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OsO", __pyx_argnames, &__pyx_v_object, &__pyx_v_event, &__pyx_v_callback))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_DECREF(__pyx_args);
  Py_DECREF(__pyx_v_args);
  __Pyx_AddTraceback("cobject.Object.monitor");
  return NULL;
  __pyx_L3:;
  __pyx_v_connection = Py_None; Py_INCREF(Py_None);

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":80
 *         with objects that have a 'destroy' signal.
 *         """
 *         connection = object.connect(event, callback, *args)             # <<<<<<<<<<<<<< 
 *         self.connect('destroyed', _on_monitor_destroyed, object,
 *                      connection)
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_object, __pyx_n_connect); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_event); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  Py_INCREF(__pyx_v_callback);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_callback);
  __pyx_2 = 0;
  __pyx_2 = PySequence_Tuple(__pyx_v_args); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyNumber_Add(((PyObject *)__pyx_3), __pyx_2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_3 = PyObject_Call(__pyx_1, __pyx_4, NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_v_connection);
  __pyx_v_connection = __pyx_3;
  __pyx_3 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":81
 *         """
 *         connection = object.connect(event, callback, *args)
 *         self.connect('destroyed', _on_monitor_destroyed, object,             # <<<<<<<<<<<<<< 
 *                      connection)
 * 
 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_connect); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n__on_monitor_destroyed); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":82
 *         connection = object.connect(event, callback, *args)
 *         self.connect('destroyed', _on_monitor_destroyed, object,
 *                      connection)             # <<<<<<<<<<<<<< 
 * 
 * #TODO: make it a static method ?
 */
  __pyx_4 = PyTuple_New(4); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_destroyed);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_n_destroyed);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  Py_INCREF(__pyx_v_object);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_v_object);
  Py_INCREF(__pyx_v_connection);
  PyTuple_SET_ITEM(__pyx_4, 3, __pyx_v_connection);
  __pyx_1 = 0;
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cobject.Object.monitor");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_connection);
  Py_DECREF(__pyx_args);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":85
 * 
 * #TODO: make it a static method ?
 * def _on_monitor_destroyed(self, object, connection):             # <<<<<<<<<<<<<< 
 *     object.disconnect(connection)
 */

static PyObject *__pyx_pf_7cobject__on_monitor_destroyed(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_7cobject__on_monitor_destroyed(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_object = 0;
  PyObject *__pyx_v_connection = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"self","object","connection",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 3)) {
    __pyx_v_self = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_object = PyTuple_GET_ITEM(__pyx_args, 1);
    __pyx_v_connection = PyTuple_GET_ITEM(__pyx_args, 2);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_object, &__pyx_v_connection))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("cobject._on_monitor_destroyed");
  return NULL;
  __pyx_L3:;

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":86
 * #TODO: make it a static method ?
 * def _on_monitor_destroyed(self, object, connection):
 *     object.disconnect(connection)             # <<<<<<<<<<<<<< 
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_object, __pyx_n_disconnect); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_connection);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_connection);
  __pyx_3 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("cobject._on_monitor_destroyed");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Exception, "Exception"},
  {&__pyx_n_GeneratorType, "GeneratorType"},
  {&__pyx_n_Tasklet, "Tasklet"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n__on_monitor_destroyed, "_on_monitor_destroyed"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_connect, "connect"},
  {&__pyx_n_connect_object, "connect_object"},
  {&__pyx_n_destroyed, "destroyed"},
  {&__pyx_n_disconnect, "disconnect"},
  {&__pyx_n_emit, "emit"},
  {&__pyx_n_generator, "generator"},
  {&__pyx_n_get, "get"},
  {&__pyx_n_id, "id"},
  {&__pyx_n_itervalues, "itervalues"},
  {&__pyx_n_monitor, "monitor"},
  {&__pyx_n_remove, "remove"},
  {&__pyx_n_setdefault, "setdefault"},
  {&__pyx_n_start, "start"},
  {&__pyx_n_types, "types"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k_3p, __pyx_k_3, sizeof(__pyx_k_3), 0},
  {&__pyx_k_5p, __pyx_k_5, sizeof(__pyx_k_5), 0},
  {0, 0, 0, 0}
};
static struct __pyx_vtabstruct_7cobject_Object __pyx_vtable_7cobject_Object;

static PyObject *__pyx_tp_new_7cobject_Object(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_7cobject_Object *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_7cobject_Object *)o);
  *(struct __pyx_vtabstruct_7cobject_Object **)&p->__pyx_vtab = __pyx_vtabptr_7cobject_Object;
  p->__listeners = ((PyObject *)Py_None); Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_7cobject_Object(PyObject *o) {
  struct __pyx_obj_7cobject_Object *p = (struct __pyx_obj_7cobject_Object *)o;
  Py_XDECREF(((PyObject *)p->__listeners));
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_7cobject_Object(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_7cobject_Object *p = (struct __pyx_obj_7cobject_Object *)o;
  if (p->__listeners) {
    e = (*v)(p->__listeners, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_7cobject_Object(PyObject *o) {
  struct __pyx_obj_7cobject_Object *p = (struct __pyx_obj_7cobject_Object *)o;
  PyObject* tmp;
  tmp = ((PyObject*)p->__listeners);
  p->__listeners = ((PyObject *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(tmp);
  return 0;
}

static struct PyMethodDef __pyx_methods_7cobject_Object[] = {
  {"connect", (PyCFunction)__pyx_pf_7cobject_6Object_connect, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7cobject_6Object_connect},
  {"connect_object", (PyCFunction)__pyx_pf_7cobject_6Object_connect_object, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7cobject_6Object_connect_object},
  {"disconnect", (PyCFunction)__pyx_pf_7cobject_6Object_disconnect, METH_O, __pyx_doc_7cobject_6Object_disconnect},
  {"emit", (PyCFunction)__pyx_pf_7cobject_6Object_emit, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7cobject_6Object_emit},
  {"monitor", (PyCFunction)__pyx_pf_7cobject_6Object_monitor, METH_VARARGS|METH_KEYWORDS, __pyx_doc_7cobject_6Object_monitor},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Object = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Object = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Object = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Object = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_7cobject_Object = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "cobject.Object", /*tp_name*/
  sizeof(struct __pyx_obj_7cobject_Object), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_7cobject_Object, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Object, /*tp_as_number*/
  &__pyx_tp_as_sequence_Object, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Object, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Object, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "This class implements the observer patern\n    \n        I could use gobject.GObject instead.\n        But i think gobject may be overkill there... still thinking about it...\n    ", /*tp_doc*/
  __pyx_tp_traverse_7cobject_Object, /*tp_traverse*/
  __pyx_tp_clear_7cobject_Object, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_7cobject_Object, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_7cobject_6Object___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_7cobject_Object, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"_on_monitor_destroyed", (PyCFunction)__pyx_pf_7cobject__on_monitor_destroyed, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initcobject(void); /*proto*/
PyMODINIT_FUNC initcobject(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("cobject", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_builtin_id = __Pyx_GetName(__pyx_b, __pyx_n_id); if (!__pyx_builtin_id) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_builtin_Exception = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_builtin_Exception) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_vtabptr_7cobject_Object = &__pyx_vtable_7cobject_Object;
  *(void(**)(void))&__pyx_vtable_7cobject_Object._emit = (void(*)(void))__pyx_f_7cobject_6Object__emit;
  *(void(**)(void))&__pyx_vtable_7cobject_Object._emit_1 = (void(*)(void))__pyx_f_7cobject_6Object__emit_1;
  if (PyType_Ready(&__pyx_type_7cobject_Object) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_7cobject_Object.tp_dict, __pyx_vtabptr_7cobject_Object) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Object", (PyObject *)&__pyx_type_7cobject_Object) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_7cobject_Object = &__pyx_type_7cobject_Object;
  /*--- Type import code ---*/
  __pyx_ptype_3geo_Vect = __Pyx_ImportType("geo", "Vect", sizeof(struct __pyx_obj_3geo_Vect)); if (unlikely(!__pyx_ptype_3geo_Vect)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_3geo_Rect = __Pyx_ImportType("geo", "Rect", sizeof(struct __pyx_obj_3geo_Rect)); if (unlikely(!__pyx_ptype_3geo_Rect)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_3geo_Rect->tp_dict, &__pyx_vtabptr_3geo_Rect) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  /*--- Function import code ---*/
  __pyx_1 = __Pyx_ImportModule("geo"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_vect_to_py", (void**)&__pyx_f_3geo_c_vect_to_py, "struct __pyx_obj_3geo_Vect *(struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_vect_equal", (void**)&__pyx_f_3geo_c_vect_equal, "int (struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_to_py", (void**)&__pyx_f_3geo_c_rect_to_py, "struct __pyx_obj_3geo_Rect *(struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_left", (void**)&__pyx_f_3geo_c_rect_left, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_right", (void**)&__pyx_f_3geo_c_rect_right, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_top", (void**)&__pyx_f_3geo_c_rect_top, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_bottom", (void**)&__pyx_f_3geo_c_rect_bottom, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_width", (void**)&__pyx_f_3geo_c_rect_width, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_height", (void**)&__pyx_f_3geo_c_rect_height, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_contains", (void**)&__pyx_f_3geo_c_rect_contains, "int (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_intersect", (void**)&__pyx_f_3geo_c_rect_intersect, "int (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_inside", (void**)&__pyx_f_3geo_c_rect_inside, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_merge", (void**)&__pyx_f_3geo_c_rect_merge, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_clip", (void**)&__pyx_f_3geo_c_rect_clip, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_move", (void**)&__pyx_f_3geo_c_rect_move, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  /*--- Execution code ---*/

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":19
 * #    along with Tichy.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * from types import GeneratorType             # <<<<<<<<<<<<<< 
 * from tichy.tasklet import Tasklet
 * 
 */
  __pyx_1 = PyList_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_GeneratorType);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_GeneratorType);
  __pyx_2 = __Pyx_Import(__pyx_n_types, ((PyObject *)__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_GeneratorType); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_GeneratorType, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":20
 * 
 * from types import GeneratorType
 * from tichy.tasklet import Tasklet             # <<<<<<<<<<<<<< 
 * 
 * cdef class Object:
 */
  __pyx_2 = PyList_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_Tasklet);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_n_Tasklet);
  __pyx_1 = __Pyx_Import(__pyx_k_3p, ((PyObject *)__pyx_2)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_Tasklet); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Tasklet, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/cobject.pyx":85
 * 
 * #TODO: make it a static method ?
 * def _on_monitor_destroyed(self, object, connection):             # <<<<<<<<<<<<<< 
 *     object.disconnect(connection)
 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("cobject");
}

static char *__pyx_filenames[] = {
  "cobject.pyx",
  "geo.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static int __Pyx_CheckKeywordStrings(
    PyObject *kwdict,
    const char* function_name,
    int kw_allowed)
{
    PyObject* key = 0;
    Py_ssize_t pos = 0;
    while (PyDict_Next(kwdict, &pos, &key, 0)) {
        if (unlikely(!PyString_Check(key))) {
            PyErr_Format(PyExc_TypeError,
                         "%s() keywords must be strings", function_name);
            return 0;
        }
    }
    if (unlikely(!kw_allowed) && unlikely(key)) {
        PyErr_Format(PyExc_TypeError,
                     "'%s' is an invalid keyword argument for this function",
                     PyString_AsString(key));
        return 0;
    }
    return 1;
}

static INLINE int __Pyx_SplitStarArg(
    PyObject **args, 
    Py_ssize_t nargs,
    PyObject **args2)
{
    PyObject *args1 = 0;
    args1 = PyTuple_GetSlice(*args, 0, nargs);
    if (!args1) {
        *args2 = 0;
        return -1;
    }
    *args2 = PyTuple_GetSlice(*args, nargs, PyTuple_GET_SIZE(*args));
    if (!*args2) {
        Py_DECREF(args1);
        return -1;
    }
    *args = args1;
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                type = 0;
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;
    
    py_name = PyString_FromString(module_name);
    if (!py_name)
        goto bad;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_name);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;
    
    py_name = PyString_FromString(name);
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr) {
    int result;
    PyObject *pycobj;
    
    pycobj = PyMapping_GetItemString(dict, "__pyx_vtable__");
    if (!pycobj)
        goto bad;
    *(void **)vtabptr = PyCObject_AsVoidPtr(pycobj);
    if (!*(void **)vtabptr)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    char *desc;
    
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%s does not export expected C function %s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    desc = (char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    if (strcmp(desc, sig) != 0) {
        PyErr_Format(PyExc_TypeError,
            "C function %s.%s has wrong signature (expected %s, got %s)",
                PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    *f = PyCObject_AsVoidPtr(cobj);
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
    }
    else {
        py_funcname = PyString_FromString(funcname);
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
