/* Generated by Cython 0.9.6.14 on Thu Nov 20 15:27:12 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static char * __pyx_cfilenm= __FILE__;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name, int exact); /*proto*/

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/

static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations */

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":19
 * #    along with Tichy.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * cdef struct c_Vect:             # <<<<<<<<<<<<<< 
 *     int x
 *     int y
 */

struct __pyx_t_3geo_c_Vect {
  int x;
  int y;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":29
 * cdef inline int c_vect_equal(c_Vect* v1, c_Vect* v2)
 * 
 * cdef struct c_Rect:             # <<<<<<<<<<<<<< 
 *     c_Vect pos
 *     c_Vect size
 */

struct __pyx_t_3geo_c_Rect {
  struct __pyx_t_3geo_c_Vect pos;
  struct __pyx_t_3geo_c_Vect size;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":33
 *     c_Vect size
 * 
 * cdef class Rect:             # <<<<<<<<<<<<<< 
 *     cdef c_Rect c_value
 *     
 */

struct __pyx_obj_3geo_Rect {
  PyObject_HEAD
  struct __pyx_vtabstruct_3geo_Rect *__pyx_vtab;
  struct __pyx_t_3geo_c_Rect c_value;
};

/* "/home/charlie/Work/tichy/tichy/guic/painter.pxd":23
 * 
 * 
 * cdef class Painter:             # <<<<<<<<<<<<<< 
 *     """ This class is used to draw all the widgets
 *         
 */

struct __pyx_obj_7painter_Painter {
  PyObject_HEAD
  struct __pyx_vtabstruct_7painter_Painter *__pyx_vtab;
  struct __pyx_t_3geo_c_Vect c_pos;
  struct __pyx_t_3geo_c_Rect c_mask;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":23
 *     int y
 * 
 * cdef class Vect:             # <<<<<<<<<<<<<< 
 *     cdef c_Vect c_value
 *     
 */

struct __pyx_obj_3geo_Vect {
  PyObject_HEAD
  struct __pyx_t_3geo_c_Vect c_value;
};


/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":33
 *     c_Vect size
 * 
 * cdef class Rect:             # <<<<<<<<<<<<<< 
 *     cdef c_Rect c_value
 *     
 */

struct __pyx_vtabstruct_3geo_Rect {
  struct __pyx_obj_3geo_Rect *(*move)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Vect *);
  struct __pyx_obj_3geo_Rect *(*clip)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  struct __pyx_obj_3geo_Rect *(*merge)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  int (*intersect)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  struct __pyx_obj_3geo_Rect *(*inside)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
};
static struct __pyx_vtabstruct_3geo_Rect *__pyx_vtabptr_3geo_Rect;


/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":9
 * from label import Label
 * 
 * cdef class Painter:             # <<<<<<<<<<<<<< 
 *     """ This class is used to draw all the widgets
 *         
 */

struct __pyx_vtabstruct_7painter_Painter {
  void (*_draw)(struct __pyx_obj_7painter_Painter *, PyObject *);
  void (*c_move)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Vect *);
  void (*c_umove)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Vect *);
  void (*c_clip)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Rect *);
  void (*c_set_mask)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Rect *);
  struct __pyx_obj_7painter_Painter *(*_to_surface)(struct __pyx_obj_7painter_Painter *, PyObject *);
  PyObject *(*c_surface_from_size)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Vect *);
  PyObject *(*_surface_from_image)(struct __pyx_obj_7painter_Painter *, char *);
  PyObject *(*_surface_from_text)(struct __pyx_obj_7painter_Painter *, PyObject *, PyObject *, PyObject *, PyObject *);
  void (*_draw_surface)(struct __pyx_obj_7painter_Painter *, PyObject *, PyObject *);
  void (*_fill)(struct __pyx_obj_7painter_Painter *, PyObject *, struct __pyx_obj_3geo_Vect *);
  void (*_draw_frame)(struct __pyx_obj_7painter_Painter *, PyObject *, struct __pyx_obj_3geo_Vect *);
  void (*_flip)(struct __pyx_obj_7painter_Painter *, struct __pyx_obj_3geo_Rect *);
};
static struct __pyx_vtabstruct_7painter_Painter *__pyx_vtabptr_7painter_Painter;

static PyTypeObject *__pyx_ptype_3geo_Vect = 0;
static PyTypeObject *__pyx_ptype_3geo_Rect = 0;
static struct __pyx_obj_3geo_Vect *(*__pyx_f_3geo_c_vect_to_py)(struct __pyx_t_3geo_c_Vect *); /*proto*/
static int (*__pyx_f_3geo_c_vect_equal)(struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Vect *); /*proto*/
static struct __pyx_obj_3geo_Rect *(*__pyx_f_3geo_c_rect_to_py)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_left)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_right)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_top)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_bottom)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_width)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_height)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_contains)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_intersect)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_inside)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_merge)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_clip)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_move)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Rect *); /*proto*/

static PyTypeObject *__pyx_ptype_7painter_Painter = 0;


/* Implementation of painter */


static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_move;
static PyObject *__pyx_n_umove;
static PyObject *__pyx_n_clip;
static PyObject *__pyx_n_set_mask;
static PyObject *__pyx_n_surface_from_size;
static PyObject *__pyx_n_draw_surface;
static PyObject *__pyx_n_fill;
static PyObject *__pyx_n_draw_frame;
static PyObject *__pyx_n_flip;
static PyObject *__pyx_n_geo;
static PyObject *__pyx_n_asvect;
static PyObject *__pyx_n_asrect;
static PyObject *__pyx_n_label;
static PyObject *__pyx_n_Label;

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":15
 *     """
 *     
 *     def __init__(self, Vect pos, Rect mask):             # <<<<<<<<<<<<<< 
 *         self.c_pos = pos.c_value
 *         self.c_mask = mask.c_value
 */

static int __pyx_pf_7painter_7Painter___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_7painter_7Painter___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_3geo_Vect *__pyx_v_pos = 0;
  struct __pyx_obj_3geo_Rect *__pyx_v_mask = 0;
  int __pyx_r;
  static char *__pyx_argnames[] = {"pos","mask",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_pos = ((struct __pyx_obj_3geo_Vect *)PyTuple_GET_ITEM(__pyx_args, 0));
    __pyx_v_mask = ((struct __pyx_obj_3geo_Rect *)PyTuple_GET_ITEM(__pyx_args, 1));
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_pos, &__pyx_v_mask))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("painter.Painter.__init__");
  return -1;
  __pyx_L3:;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_pos), __pyx_ptype_3geo_Vect, 1, "pos", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_mask), __pyx_ptype_3geo_Rect, 1, "mask", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":16
 *     
 *     def __init__(self, Vect pos, Rect mask):
 *         self.c_pos = pos.c_value             # <<<<<<<<<<<<<< 
 *         self.c_mask = mask.c_value
 *         
 */
  ((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->c_pos = __pyx_v_pos->c_value;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":17
 *     def __init__(self, Vect pos, Rect mask):
 *         self.c_pos = pos.c_value
 *         self.c_mask = mask.c_value             # <<<<<<<<<<<<<< 
 *         
 *     property pos:
 */
  ((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->c_mask = __pyx_v_mask->c_value;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("painter.Painter.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":20
 *         
 *     property pos:
 *         def __get__(self): return c_vect_to_py(&self.c_pos)             # <<<<<<<<<<<<<< 
 *     property mask:
 *         def __get__(self): return c_rect_to_py(&self.c_mask)
 */

static PyObject *__pyx_pf_7painter_7Painter_3pos___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_3pos___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_1 = ((PyObject *)__pyx_f_3geo_c_vect_to_py((&((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->c_pos))); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("painter.Painter.pos.__get__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":22
 *         def __get__(self): return c_vect_to_py(&self.c_pos)
 *     property mask:
 *         def __get__(self): return c_rect_to_py(&self.c_mask)             # <<<<<<<<<<<<<< 
 * 
 *     cdef void c_move(self, c_Vect *v):
 */

static PyObject *__pyx_pf_7painter_7Painter_4mask___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_4mask___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_1 = ((PyObject *)__pyx_f_3geo_c_rect_to_py((&((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->c_mask))); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("painter.Painter.mask.__get__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":24
 *         def __get__(self): return c_rect_to_py(&self.c_mask)
 * 
 *     cdef void c_move(self, c_Vect *v):             # <<<<<<<<<<<<<< 
 *         self.c_pos.x += v.x; self.c_pos.y += v.y
 *         self.c_mask.pos.x -= v.x; self.c_mask.pos.y -= v.y
 */

static  void __pyx_f_7painter_7Painter_c_move(struct __pyx_obj_7painter_Painter *__pyx_v_self, struct __pyx_t_3geo_c_Vect *__pyx_v_v) {

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":25
 * 
 *     cdef void c_move(self, c_Vect *v):
 *         self.c_pos.x += v.x; self.c_pos.y += v.y             # <<<<<<<<<<<<<< 
 *         self.c_mask.pos.x -= v.x; self.c_mask.pos.y -= v.y
 *     def move(self, Vect v): self.c_move(&v.c_value)
 */
  __pyx_v_self->c_pos.x += __pyx_v_v->x;
  __pyx_v_self->c_pos.y += __pyx_v_v->y;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":26
 *     cdef void c_move(self, c_Vect *v):
 *         self.c_pos.x += v.x; self.c_pos.y += v.y
 *         self.c_mask.pos.x -= v.x; self.c_mask.pos.y -= v.y             # <<<<<<<<<<<<<< 
 *     def move(self, Vect v): self.c_move(&v.c_value)
 *         
 */
  __pyx_v_self->c_mask.pos.x -= __pyx_v_v->x;
  __pyx_v_self->c_mask.pos.y -= __pyx_v_v->y;

}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":27
 *         self.c_pos.x += v.x; self.c_pos.y += v.y
 *         self.c_mask.pos.x -= v.x; self.c_mask.pos.y -= v.y
 *     def move(self, Vect v): self.c_move(&v.c_value)             # <<<<<<<<<<<<<< 
 *         
 *     cdef void c_umove(self, c_Vect *v):
 */

static PyObject *__pyx_pf_7painter_7Painter_move(PyObject *__pyx_v_self, PyObject *__pyx_v_v); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_move(PyObject *__pyx_v_self, PyObject *__pyx_v_v) {
  PyObject *__pyx_r;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_v), __pyx_ptype_3geo_Vect, 1, "v", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_7painter_Painter *)((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->__pyx_vtab)->c_move(((struct __pyx_obj_7painter_Painter *)__pyx_v_self), (&((struct __pyx_obj_3geo_Vect *)__pyx_v_v)->c_value));

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("painter.Painter.move");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":29
 *     def move(self, Vect v): self.c_move(&v.c_value)
 *         
 *     cdef void c_umove(self, c_Vect *v):             # <<<<<<<<<<<<<< 
 *         self.c_pos.x -= v.x; self.c_pos.y -= v.y
 *         self.c_mask.pos.x += v.x; self.c_mask.pos.y += v.y
 */

static  void __pyx_f_7painter_7Painter_c_umove(struct __pyx_obj_7painter_Painter *__pyx_v_self, struct __pyx_t_3geo_c_Vect *__pyx_v_v) {

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":30
 *         
 *     cdef void c_umove(self, c_Vect *v):
 *         self.c_pos.x -= v.x; self.c_pos.y -= v.y             # <<<<<<<<<<<<<< 
 *         self.c_mask.pos.x += v.x; self.c_mask.pos.y += v.y
 *     def umove(self, Vect v): self.c_umove(&v.c_value)
 */
  __pyx_v_self->c_pos.x -= __pyx_v_v->x;
  __pyx_v_self->c_pos.y -= __pyx_v_v->y;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":31
 *     cdef void c_umove(self, c_Vect *v):
 *         self.c_pos.x -= v.x; self.c_pos.y -= v.y
 *         self.c_mask.pos.x += v.x; self.c_mask.pos.y += v.y             # <<<<<<<<<<<<<< 
 *     def umove(self, Vect v): self.c_umove(&v.c_value)
 *         
 */
  __pyx_v_self->c_mask.pos.x += __pyx_v_v->x;
  __pyx_v_self->c_mask.pos.y += __pyx_v_v->y;

}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":32
 *         self.c_pos.x -= v.x; self.c_pos.y -= v.y
 *         self.c_mask.pos.x += v.x; self.c_mask.pos.y += v.y
 *     def umove(self, Vect v): self.c_umove(&v.c_value)             # <<<<<<<<<<<<<< 
 *         
 *     cdef void c_clip(self, c_Rect *r):
 */

static PyObject *__pyx_pf_7painter_7Painter_umove(PyObject *__pyx_v_self, PyObject *__pyx_v_v); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_umove(PyObject *__pyx_v_self, PyObject *__pyx_v_v) {
  PyObject *__pyx_r;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_v), __pyx_ptype_3geo_Vect, 1, "v", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_7painter_Painter *)((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->__pyx_vtab)->c_umove(((struct __pyx_obj_7painter_Painter *)__pyx_v_self), (&((struct __pyx_obj_3geo_Vect *)__pyx_v_v)->c_value));

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("painter.Painter.umove");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":34
 *     def umove(self, Vect v): self.c_umove(&v.c_value)
 *         
 *     cdef void c_clip(self, c_Rect *r):             # <<<<<<<<<<<<<< 
 *         cdef c_Rect mask
 *         c_rect_clip(&self.c_mask, r, &mask)
 */

static  void __pyx_f_7painter_7Painter_c_clip(struct __pyx_obj_7painter_Painter *__pyx_v_self, struct __pyx_t_3geo_c_Rect *__pyx_v_r) {
  struct __pyx_t_3geo_c_Rect __pyx_v_mask;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":36
 *     cdef void c_clip(self, c_Rect *r):
 *         cdef c_Rect mask
 *         c_rect_clip(&self.c_mask, r, &mask)             # <<<<<<<<<<<<<< 
 *         self.c_set_mask(&mask)
 *     def clip(self, Rect r): self.c_clip(&r.c_value)
 */
  __pyx_f_3geo_c_rect_clip((&__pyx_v_self->c_mask), __pyx_v_r, (&__pyx_v_mask));

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":37
 *         cdef c_Rect mask
 *         c_rect_clip(&self.c_mask, r, &mask)
 *         self.c_set_mask(&mask)             # <<<<<<<<<<<<<< 
 *     def clip(self, Rect r): self.c_clip(&r.c_value)
 *         
 */
  ((struct __pyx_vtabstruct_7painter_Painter *)__pyx_v_self->__pyx_vtab)->c_set_mask(__pyx_v_self, (&__pyx_v_mask));

}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":38
 *         c_rect_clip(&self.c_mask, r, &mask)
 *         self.c_set_mask(&mask)
 *     def clip(self, Rect r): self.c_clip(&r.c_value)             # <<<<<<<<<<<<<< 
 *         
 *     cdef void c_set_mask(self, c_Rect *r):
 */

static PyObject *__pyx_pf_7painter_7Painter_clip(PyObject *__pyx_v_self, PyObject *__pyx_v_r); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_clip(PyObject *__pyx_v_self, PyObject *__pyx_v_r) {
  PyObject *__pyx_r;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_r), __pyx_ptype_3geo_Rect, 1, "r", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_7painter_Painter *)((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->__pyx_vtab)->c_clip(((struct __pyx_obj_7painter_Painter *)__pyx_v_self), (&((struct __pyx_obj_3geo_Rect *)__pyx_v_r)->c_value));

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("painter.Painter.clip");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":40
 *     def clip(self, Rect r): self.c_clip(&r.c_value)
 *         
 *     cdef void c_set_mask(self, c_Rect *r):             # <<<<<<<<<<<<<< 
 *         self.c_mask = r[0]
 *     def set_mask(self, Rect r): self.c_set_mask(&r.c_value)
 */

static  void __pyx_f_7painter_7Painter_c_set_mask(struct __pyx_obj_7painter_Painter *__pyx_v_self, struct __pyx_t_3geo_c_Rect *__pyx_v_r) {

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":41
 *         
 *     cdef void c_set_mask(self, c_Rect *r):
 *         self.c_mask = r[0]             # <<<<<<<<<<<<<< 
 *     def set_mask(self, Rect r): self.c_set_mask(&r.c_value)
 *         
 */
  __pyx_v_self->c_mask = (__pyx_v_r[0]);

}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":42
 *     cdef void c_set_mask(self, c_Rect *r):
 *         self.c_mask = r[0]
 *     def set_mask(self, Rect r): self.c_set_mask(&r.c_value)             # <<<<<<<<<<<<<< 
 *         
 *     cdef Painter _to_surface(self, surf):
 */

static PyObject *__pyx_pf_7painter_7Painter_set_mask(PyObject *__pyx_v_self, PyObject *__pyx_v_r); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_set_mask(PyObject *__pyx_v_self, PyObject *__pyx_v_r) {
  PyObject *__pyx_r;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_r), __pyx_ptype_3geo_Rect, 1, "r", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_7painter_Painter *)((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->__pyx_vtab)->c_set_mask(((struct __pyx_obj_7painter_Painter *)__pyx_v_self), (&((struct __pyx_obj_3geo_Rect *)__pyx_v_r)->c_value));

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("painter.Painter.set_mask");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":44
 *     def set_mask(self, Rect r): self.c_set_mask(&r.c_value)
 *         
 *     cdef Painter _to_surface(self, surf):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError
 *             
 */

static PyObject *__pyx_n_NotImplementedError;

static PyObject *__pyx_builtin_NotImplementedError;

static  struct __pyx_obj_7painter_Painter *__pyx_f_7painter_7Painter__to_surface(struct __pyx_obj_7painter_Painter *__pyx_v_self, PyObject *__pyx_v_surf) {
  struct __pyx_obj_7painter_Painter *__pyx_r;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":45
 *         
 *     cdef Painter _to_surface(self, surf):
 *         raise NotImplementedError             # <<<<<<<<<<<<<< 
 *             
 *     cdef void _draw(self, o):
 */
  __Pyx_Raise(__pyx_builtin_NotImplementedError, 0, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = ((struct __pyx_obj_7painter_Painter *)Py_None); Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("painter.Painter._to_surface");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":47
 *         raise NotImplementedError
 *             
 *     cdef void _draw(self, o):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError
 *         
 */

static  void __pyx_f_7painter_7Painter__draw(struct __pyx_obj_7painter_Painter *__pyx_v_self, PyObject *__pyx_v_o) {

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":48
 *             
 *     cdef void _draw(self, o):
 *         raise NotImplementedError             # <<<<<<<<<<<<<< 
 *         
 *     cdef c_surface_from_size(self, c_Vect *size):
 */
  __Pyx_Raise(__pyx_builtin_NotImplementedError, 0, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("painter.Painter._draw");
  __pyx_L0:;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":50
 *         raise NotImplementedError
 *         
 *     cdef c_surface_from_size(self, c_Vect *size):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError
 *     def surface_from_size(self, Vect v):
 */

static  PyObject *__pyx_f_7painter_7Painter_c_surface_from_size(struct __pyx_obj_7painter_Painter *__pyx_v_self, struct __pyx_t_3geo_c_Vect *__pyx_v_size) {
  PyObject *__pyx_r;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":51
 *         
 *     cdef c_surface_from_size(self, c_Vect *size):
 *         raise NotImplementedError             # <<<<<<<<<<<<<< 
 *     def surface_from_size(self, Vect v):
 *         self.c_surface_from_size(&v.c_value)
 */
  __Pyx_Raise(__pyx_builtin_NotImplementedError, 0, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("painter.Painter.c_surface_from_size");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":52
 *     cdef c_surface_from_size(self, c_Vect *size):
 *         raise NotImplementedError
 *     def surface_from_size(self, Vect v):             # <<<<<<<<<<<<<< 
 *         self.c_surface_from_size(&v.c_value)
 *         
 */

static PyObject *__pyx_pf_7painter_7Painter_surface_from_size(PyObject *__pyx_v_self, PyObject *__pyx_v_v); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_surface_from_size(PyObject *__pyx_v_self, PyObject *__pyx_v_v) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_v), __pyx_ptype_3geo_Vect, 1, "v", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":53
 *         raise NotImplementedError
 *     def surface_from_size(self, Vect v):
 *         self.c_surface_from_size(&v.c_value)             # <<<<<<<<<<<<<< 
 *         
 *     cdef _surface_from_image(self, char* path):
 */
  __pyx_1 = ((struct __pyx_vtabstruct_7painter_Painter *)((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->__pyx_vtab)->c_surface_from_size(((struct __pyx_obj_7painter_Painter *)__pyx_v_self), (&((struct __pyx_obj_3geo_Vect *)__pyx_v_v)->c_value)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("painter.Painter.surface_from_size");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":55
 *         self.c_surface_from_size(&v.c_value)
 *         
 *     cdef _surface_from_image(self, char* path):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError
 *         
 */

static  PyObject *__pyx_f_7painter_7Painter__surface_from_image(struct __pyx_obj_7painter_Painter *__pyx_v_self, char *__pyx_v_path) {
  PyObject *__pyx_r;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":56
 *         
 *     cdef _surface_from_image(self, char* path):
 *         raise NotImplementedError             # <<<<<<<<<<<<<< 
 *         
 *     cdef _surface_from_text(self, font, text, color, length):
 */
  __Pyx_Raise(__pyx_builtin_NotImplementedError, 0, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("painter.Painter._surface_from_image");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":58
 *         raise NotImplementedError
 *         
 *     cdef _surface_from_text(self, font, text, color, length):             # <<<<<<<<<<<<<< 
 *         """Create a new surface from a text"""
 *         raise NotImplementedError
 */

static  PyObject *__pyx_f_7painter_7Painter__surface_from_text(struct __pyx_obj_7painter_Painter *__pyx_v_self, PyObject *__pyx_v_font, PyObject *__pyx_v_text, PyObject *__pyx_v_color, PyObject *__pyx_v_length) {
  PyObject *__pyx_r;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":60
 *     cdef _surface_from_text(self, font, text, color, length):
 *         """Create a new surface from a text"""
 *         raise NotImplementedError             # <<<<<<<<<<<<<< 
 *     
 *     cdef void _draw_surface(self, surf, area):
 */
  __Pyx_Raise(__pyx_builtin_NotImplementedError, 0, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("painter.Painter._surface_from_text");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":62
 *         raise NotImplementedError
 *     
 *     cdef void _draw_surface(self, surf, area):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError
 *     def draw_surface(self, surf, area = None): self._draw_surface(surf, area)
 */

static  void __pyx_f_7painter_7Painter__draw_surface(struct __pyx_obj_7painter_Painter *__pyx_v_self, PyObject *__pyx_v_surf, PyObject *__pyx_v_area) {

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":63
 *     
 *     cdef void _draw_surface(self, surf, area):
 *         raise NotImplementedError             # <<<<<<<<<<<<<< 
 *     def draw_surface(self, surf, area = None): self._draw_surface(surf, area)
 *     
 */
  __Pyx_Raise(__pyx_builtin_NotImplementedError, 0, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1;}

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("painter.Painter._draw_surface");
  __pyx_L0:;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":64
 *     cdef void _draw_surface(self, surf, area):
 *         raise NotImplementedError
 *     def draw_surface(self, surf, area = None): self._draw_surface(surf, area)             # <<<<<<<<<<<<<< 
 *     
 *     cdef void _fill(self, color, Vect size):
 */

static PyObject *__pyx_pf_7painter_7Painter_draw_surface(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_draw_surface(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_surf = 0;
  PyObject *__pyx_v_area = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"surf","area",0};
  __pyx_v_area = Py_None;
  if (likely(!__pyx_kwds) && likely(1 <= PyTuple_GET_SIZE(__pyx_args)) && likely(PyTuple_GET_SIZE(__pyx_args) <= 2)) {
    __pyx_v_surf = PyTuple_GET_ITEM(__pyx_args, 0);
    if (PyTuple_GET_SIZE(__pyx_args) > 1) {
      __pyx_v_area = PyTuple_GET_ITEM(__pyx_args, 1);
    }
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_surf, &__pyx_v_area))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("painter.Painter.draw_surface");
  return NULL;
  __pyx_L3:;
  ((struct __pyx_vtabstruct_7painter_Painter *)((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->__pyx_vtab)->_draw_surface(((struct __pyx_obj_7painter_Painter *)__pyx_v_self), __pyx_v_surf, __pyx_v_area);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":66
 *     def draw_surface(self, surf, area = None): self._draw_surface(surf, area)
 *     
 *     cdef void _fill(self, color, Vect size):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError
 *     def fill(self, color, size): self._fill(color, asvect(size))
 */

static  void __pyx_f_7painter_7Painter__fill(struct __pyx_obj_7painter_Painter *__pyx_v_self, PyObject *__pyx_v_color, struct __pyx_obj_3geo_Vect *__pyx_v_size) {

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":67
 *     
 *     cdef void _fill(self, color, Vect size):
 *         raise NotImplementedError             # <<<<<<<<<<<<<< 
 *     def fill(self, color, size): self._fill(color, asvect(size))
 * 
 */
  __Pyx_Raise(__pyx_builtin_NotImplementedError, 0, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("painter.Painter._fill");
  __pyx_L0:;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":68
 *     cdef void _fill(self, color, Vect size):
 *         raise NotImplementedError
 *     def fill(self, color, size): self._fill(color, asvect(size))             # <<<<<<<<<<<<<< 
 * 
 *     cdef void _draw_frame(self, frame, Vect size):
 */

static PyObject *__pyx_pf_7painter_7Painter_fill(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_fill(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_color = 0;
  PyObject *__pyx_v_size = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"color","size",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_color = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_size = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_color, &__pyx_v_size))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("painter.Painter.fill");
  return NULL;
  __pyx_L3:;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_asvect); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_size);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_size);
  __pyx_3 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  if (!(__Pyx_TypeTest(__pyx_3, __pyx_ptype_3geo_Vect))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_7painter_Painter *)((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->__pyx_vtab)->_fill(((struct __pyx_obj_7painter_Painter *)__pyx_v_self), __pyx_v_color, ((struct __pyx_obj_3geo_Vect *)__pyx_3));
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("painter.Painter.fill");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":70
 *     def fill(self, color, size): self._fill(color, asvect(size))
 * 
 *     cdef void _draw_frame(self, frame, Vect size):             # <<<<<<<<<<<<<< 
 *         raise NotImplementedError
 *     def draw_frame(self, frame, size): self._draw_frame(frame, asvect(size))
 */

static  void __pyx_f_7painter_7Painter__draw_frame(struct __pyx_obj_7painter_Painter *__pyx_v_self, PyObject *__pyx_v_frame, struct __pyx_obj_3geo_Vect *__pyx_v_size) {

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":71
 * 
 *     cdef void _draw_frame(self, frame, Vect size):
 *         raise NotImplementedError             # <<<<<<<<<<<<<< 
 *     def draw_frame(self, frame, size): self._draw_frame(frame, asvect(size))
 *             
 */
  __Pyx_Raise(__pyx_builtin_NotImplementedError, 0, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("painter.Painter._draw_frame");
  __pyx_L0:;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":72
 *     cdef void _draw_frame(self, frame, Vect size):
 *         raise NotImplementedError
 *     def draw_frame(self, frame, size): self._draw_frame(frame, asvect(size))             # <<<<<<<<<<<<<< 
 *             
 *     cdef void _flip(self, Rect rect):
 */

static PyObject *__pyx_pf_7painter_7Painter_draw_frame(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_draw_frame(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_frame = 0;
  PyObject *__pyx_v_size = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"frame","size",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_frame = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_size = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_frame, &__pyx_v_size))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("painter.Painter.draw_frame");
  return NULL;
  __pyx_L3:;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_asvect); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_size);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_size);
  __pyx_3 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  if (!(__Pyx_TypeTest(__pyx_3, __pyx_ptype_3geo_Vect))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_7painter_Painter *)((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->__pyx_vtab)->_draw_frame(((struct __pyx_obj_7painter_Painter *)__pyx_v_self), __pyx_v_frame, ((struct __pyx_obj_3geo_Vect *)__pyx_3));
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("painter.Painter.draw_frame");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":74
 *     def draw_frame(self, frame, size): self._draw_frame(frame, asvect(size))
 *             
 *     cdef void _flip(self, Rect rect):             # <<<<<<<<<<<<<< 
 *         pass
 *     def flip(self, r): self._flip(asrect(r))
 */

static  void __pyx_f_7painter_7Painter__flip(struct __pyx_obj_7painter_Painter *__pyx_v_self, struct __pyx_obj_3geo_Rect *__pyx_v_rect) {

}

/* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":76
 *     cdef void _flip(self, Rect rect):
 *         pass
 *     def flip(self, r): self._flip(asrect(r))             # <<<<<<<<<<<<<< 
 *     
 */

static PyObject *__pyx_pf_7painter_7Painter_flip(PyObject *__pyx_v_self, PyObject *__pyx_v_r); /*proto*/
static PyObject *__pyx_pf_7painter_7Painter_flip(PyObject *__pyx_v_self, PyObject *__pyx_v_r) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_asrect); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_r);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_r);
  __pyx_3 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  if (!(__Pyx_TypeTest(__pyx_3, __pyx_ptype_3geo_Rect))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; __pyx_clineno = __LINE__; goto __pyx_L1;}
  ((struct __pyx_vtabstruct_7painter_Painter *)((struct __pyx_obj_7painter_Painter *)__pyx_v_self)->__pyx_vtab)->_flip(((struct __pyx_obj_7painter_Painter *)__pyx_v_self), ((struct __pyx_obj_3geo_Rect *)__pyx_3));
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("painter.Painter.flip");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Label, "Label"},
  {&__pyx_n_NotImplementedError, "NotImplementedError"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n_asrect, "asrect"},
  {&__pyx_n_asvect, "asvect"},
  {&__pyx_n_clip, "clip"},
  {&__pyx_n_draw_frame, "draw_frame"},
  {&__pyx_n_draw_surface, "draw_surface"},
  {&__pyx_n_fill, "fill"},
  {&__pyx_n_flip, "flip"},
  {&__pyx_n_geo, "geo"},
  {&__pyx_n_label, "label"},
  {&__pyx_n_move, "move"},
  {&__pyx_n_set_mask, "set_mask"},
  {&__pyx_n_surface_from_size, "surface_from_size"},
  {&__pyx_n_umove, "umove"},
  {0, 0}
};
static struct __pyx_vtabstruct_7painter_Painter __pyx_vtable_7painter_Painter;

static PyObject *__pyx_tp_new_7painter_Painter(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_7painter_Painter *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_7painter_Painter *)o);
  *(struct __pyx_vtabstruct_7painter_Painter **)&p->__pyx_vtab = __pyx_vtabptr_7painter_Painter;
  return o;
}

static void __pyx_tp_dealloc_7painter_Painter(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static PyObject *__pyx_getprop_7painter_7Painter_pos(PyObject *o, void *x) {
  return __pyx_pf_7painter_7Painter_3pos___get__(o);
}

static PyObject *__pyx_getprop_7painter_7Painter_mask(PyObject *o, void *x) {
  return __pyx_pf_7painter_7Painter_4mask___get__(o);
}

static struct PyMethodDef __pyx_methods_7painter_Painter[] = {
  {"move", (PyCFunction)__pyx_pf_7painter_7Painter_move, METH_O, 0},
  {"umove", (PyCFunction)__pyx_pf_7painter_7Painter_umove, METH_O, 0},
  {"clip", (PyCFunction)__pyx_pf_7painter_7Painter_clip, METH_O, 0},
  {"set_mask", (PyCFunction)__pyx_pf_7painter_7Painter_set_mask, METH_O, 0},
  {"surface_from_size", (PyCFunction)__pyx_pf_7painter_7Painter_surface_from_size, METH_O, 0},
  {"draw_surface", (PyCFunction)__pyx_pf_7painter_7Painter_draw_surface, METH_VARARGS|METH_KEYWORDS, 0},
  {"fill", (PyCFunction)__pyx_pf_7painter_7Painter_fill, METH_VARARGS|METH_KEYWORDS, 0},
  {"draw_frame", (PyCFunction)__pyx_pf_7painter_7Painter_draw_frame, METH_VARARGS|METH_KEYWORDS, 0},
  {"flip", (PyCFunction)__pyx_pf_7painter_7Painter_flip, METH_O, 0},
  {0, 0, 0, 0}
};

static struct PyGetSetDef __pyx_getsets_7painter_Painter[] = {
  {"pos", __pyx_getprop_7painter_7Painter_pos, 0, 0, 0},
  {"mask", __pyx_getprop_7painter_7Painter_mask, 0, 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Painter = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Painter = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Painter = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Painter = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_7painter_Painter = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "painter.Painter", /*tp_name*/
  sizeof(struct __pyx_obj_7painter_Painter), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_7painter_Painter, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Painter, /*tp_as_number*/
  &__pyx_tp_as_sequence_Painter, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Painter, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Painter, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  " This class is used to draw all the widgets\n        \n        Te idea is to subclass it when we want special drawing style.\n    ", /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_7painter_Painter, /*tp_methods*/
  0, /*tp_members*/
  __pyx_getsets_7painter_Painter, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_7painter_7Painter___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_7painter_Painter, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initpainter(void); /*proto*/
PyMODINIT_FUNC initpainter(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("painter", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- String init code ---*/
  /*--- Builtin init code ---*/
  __pyx_builtin_NotImplementedError = __Pyx_GetName(__pyx_b, __pyx_n_NotImplementedError); if (!__pyx_builtin_NotImplementedError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_vtabptr_7painter_Painter = &__pyx_vtable_7painter_Painter;
  *(void(**)(void))&__pyx_vtable_7painter_Painter._draw = (void(*)(void))__pyx_f_7painter_7Painter__draw;
  *(void(**)(void))&__pyx_vtable_7painter_Painter.c_move = (void(*)(void))__pyx_f_7painter_7Painter_c_move;
  *(void(**)(void))&__pyx_vtable_7painter_Painter.c_umove = (void(*)(void))__pyx_f_7painter_7Painter_c_umove;
  *(void(**)(void))&__pyx_vtable_7painter_Painter.c_clip = (void(*)(void))__pyx_f_7painter_7Painter_c_clip;
  *(void(**)(void))&__pyx_vtable_7painter_Painter.c_set_mask = (void(*)(void))__pyx_f_7painter_7Painter_c_set_mask;
  *(void(**)(void))&__pyx_vtable_7painter_Painter._to_surface = (void(*)(void))__pyx_f_7painter_7Painter__to_surface;
  *(void(**)(void))&__pyx_vtable_7painter_Painter.c_surface_from_size = (void(*)(void))__pyx_f_7painter_7Painter_c_surface_from_size;
  *(void(**)(void))&__pyx_vtable_7painter_Painter._surface_from_image = (void(*)(void))__pyx_f_7painter_7Painter__surface_from_image;
  *(void(**)(void))&__pyx_vtable_7painter_Painter._surface_from_text = (void(*)(void))__pyx_f_7painter_7Painter__surface_from_text;
  *(void(**)(void))&__pyx_vtable_7painter_Painter._draw_surface = (void(*)(void))__pyx_f_7painter_7Painter__draw_surface;
  *(void(**)(void))&__pyx_vtable_7painter_Painter._fill = (void(*)(void))__pyx_f_7painter_7Painter__fill;
  *(void(**)(void))&__pyx_vtable_7painter_Painter._draw_frame = (void(*)(void))__pyx_f_7painter_7Painter__draw_frame;
  *(void(**)(void))&__pyx_vtable_7painter_Painter._flip = (void(*)(void))__pyx_f_7painter_7Painter__flip;
  if (PyType_Ready(&__pyx_type_7painter_Painter) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_7painter_Painter.tp_dict, __pyx_vtabptr_7painter_Painter) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Painter", (PyObject *)&__pyx_type_7painter_Painter) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_7painter_Painter = &__pyx_type_7painter_Painter;
  /*--- Type import code ---*/
  __pyx_ptype_3geo_Vect = __Pyx_ImportType("geo", "Vect", sizeof(struct __pyx_obj_3geo_Vect)); if (unlikely(!__pyx_ptype_3geo_Vect)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_3geo_Rect = __Pyx_ImportType("geo", "Rect", sizeof(struct __pyx_obj_3geo_Rect)); if (unlikely(!__pyx_ptype_3geo_Rect)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_3geo_Rect->tp_dict, &__pyx_vtabptr_3geo_Rect) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  /*--- Function import code ---*/
  __pyx_1 = __Pyx_ImportModule("geo"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_vect_to_py", (void**)&__pyx_f_3geo_c_vect_to_py, "struct __pyx_obj_3geo_Vect *(struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_vect_equal", (void**)&__pyx_f_3geo_c_vect_equal, "int (struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_to_py", (void**)&__pyx_f_3geo_c_rect_to_py, "struct __pyx_obj_3geo_Rect *(struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_left", (void**)&__pyx_f_3geo_c_rect_left, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_right", (void**)&__pyx_f_3geo_c_rect_right, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_top", (void**)&__pyx_f_3geo_c_rect_top, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_bottom", (void**)&__pyx_f_3geo_c_rect_bottom, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_width", (void**)&__pyx_f_3geo_c_rect_width, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_height", (void**)&__pyx_f_3geo_c_rect_height, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_contains", (void**)&__pyx_f_3geo_c_rect_contains, "int (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_intersect", (void**)&__pyx_f_3geo_c_rect_intersect, "int (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_inside", (void**)&__pyx_f_3geo_c_rect_inside, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_merge", (void**)&__pyx_f_3geo_c_rect_merge, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_clip", (void**)&__pyx_f_3geo_c_rect_clip, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_move", (void**)&__pyx_f_3geo_c_rect_move, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  /*--- Execution code ---*/

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":5
 * cimport geo
 * from geo cimport Vect, Rect, c_Vect, c_Rect, c_vect_to_py, c_rect_to_py, c_rect_clip
 * from geo import asvect, asrect             # <<<<<<<<<<<<<< 
 * 
 * from label import Label
 */
  __pyx_1 = PyList_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_asvect);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_asvect);
  Py_INCREF(__pyx_n_asrect);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_n_asrect);
  __pyx_2 = __Pyx_Import(__pyx_n_geo, ((PyObject *)__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_asvect); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_asvect, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_asrect); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_asrect, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":7
 * from geo import asvect, asrect
 * 
 * from label import Label             # <<<<<<<<<<<<<< 
 * 
 * cdef class Painter:
 */
  __pyx_2 = PyList_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_n_Label);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_n_Label);
  __pyx_1 = __Pyx_Import(__pyx_n_label, ((PyObject *)__pyx_2)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_Label); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Label, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/painter.pyx":76
 *     cdef void _flip(self, Rect rect):
 *         pass
 *     def flip(self, r): self._flip(asrect(r))             # <<<<<<<<<<<<<< 
 *     
 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("painter");
}

static char *__pyx_filenames[] = {
  "painter.pyx",
  "geo.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name, int exact) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (none_allowed && obj == Py_None) return 1;
    else if (exact) {
        if (obj->ob_type == type) return 1;
    }
    else {
        if (PyObject_TypeCheck(obj, type)) return 1;
    }
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                type = 0;
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;
    
    py_name = PyString_FromString(module_name);
    if (!py_name)
        goto bad;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_name);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;
    
    py_name = PyString_FromString(name);
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr) {
    int result;
    PyObject *pycobj;
    
    pycobj = PyMapping_GetItemString(dict, "__pyx_vtable__");
    if (!pycobj)
        goto bad;
    *(void **)vtabptr = PyCObject_AsVoidPtr(pycobj);
    if (!*(void **)vtabptr)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    char *desc;
    
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%s does not export expected C function %s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    desc = (char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    if (strcmp(desc, sig) != 0) {
        PyErr_Format(PyExc_TypeError,
            "C function %s.%s has wrong signature (expected %s, got %s)",
                PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    *f = PyCObject_AsVoidPtr(cobj);
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
    }
    else {
        py_funcname = PyString_FromString(funcname);
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
