/* Generated by Cython 0.9.6.14 on Tue Sep 16 12:33:28 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static char * __pyx_cfilenm= __FILE__;
static char *__pyx_filename;
static char **__pyx_f;

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static int __Pyx_SplitKeywords(PyObject **kwds, char *kwd_list[],     PyObject **kwds2, char rqd_kwds[]); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations */

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":19
 * #    along with Tichy.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * cdef struct c_Vect:             # <<<<<<<<<<<<<< 
 *     int x
 *     int y
 */

struct __pyx_t_3geo_c_Vect {
  int x;
  int y;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":29
 * cdef inline int c_vect_equal(c_Vect* v1, c_Vect* v2)
 * 
 * cdef struct c_Rect:             # <<<<<<<<<<<<<< 
 *     c_Vect pos
 *     c_Vect size
 */

struct __pyx_t_3geo_c_Rect {
  struct __pyx_t_3geo_c_Vect pos;
  struct __pyx_t_3geo_c_Vect size;
};

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pxd":22
 * from geo cimport Vect
 * 
 * cdef class Object:             # <<<<<<<<<<<<<< 
 *     cdef void _emit(self, char* event) except *
 *     cdef void _emit_1(self, char* event, v) except *
 */

struct __pyx_obj_7cobject_Object {
  PyObject_HEAD
  struct __pyx_vtabstruct_7cobject_Object *__pyx_vtab;
  PyObject *__listeners;
};

/* "/home/charlie/Work/tichy/tichy/guic/widget.pxd":30
 * # XXX: the names of the attributes are totally crazy !!!
 * 
 * cdef class Widget(Object):             # <<<<<<<<<<<<<< 
 *     cdef readonly Rect rect
 *     cdef readonly Vect _pos
 */

struct __pyx_obj_6widget_Widget {
  struct __pyx_obj_7cobject_Object __pyx_base;
  struct __pyx_obj_3geo_Rect *rect;
  struct __pyx_obj_3geo_Vect *_pos;
  struct __pyx_obj_6widget_Widget *parent;
  PyObject *item;
  PyObject *tags;
  PyObject *surface;
  int store_surface;
  PyObject *_style;
  PyObject *style_dict;
  struct __pyx_obj_3geo_Vect *_optimal_size;
  int fixed_optimal_size;
  struct __pyx_obj_3geo_Vect *_min_size;
  int fixed_min_size;
  int expand;
  int _organized;
  int _resized;
  int resizable;
  PyObject *children;
  struct __pyx_obj_6widget_Widget *focused;
  int clickable;
};

/* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":13
 * import pygame
 * 
 * cdef class SurfWidget(Widget):             # <<<<<<<<<<<<<< 
 *     def __init__(self, parent, size, **kargs):
 *         super(SurfWidget, self).__init__(parent, optimal_size = size, **kargs)
 */

struct __pyx_obj_11surf_widget_SurfWidget {
  struct __pyx_obj_6widget_Widget __pyx_base;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":33
 *     c_Vect size
 * 
 * cdef class Rect:             # <<<<<<<<<<<<<< 
 *     cdef c_Rect c_value
 *     
 */

struct __pyx_obj_3geo_Rect {
  PyObject_HEAD
  struct __pyx_vtabstruct_3geo_Rect *__pyx_vtab;
  struct __pyx_t_3geo_c_Rect c_value;
};

/* "/home/charlie/Work/tichy/tichy/guic/painter.pxd":23
 * 
 * 
 * cdef class Painter:             # <<<<<<<<<<<<<< 
 *     """ This class is used to draw all the widgets
 *         
 */

struct __pyx_obj_7painter_Painter {
  PyObject_HEAD
  struct __pyx_vtabstruct_7painter_Painter *__pyx_vtab;
  struct __pyx_t_3geo_c_Vect c_pos;
  struct __pyx_t_3geo_c_Rect c_mask;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":23
 *     int y
 * 
 * cdef class Vect:             # <<<<<<<<<<<<<< 
 *     cdef c_Vect c_value
 *     
 */

struct __pyx_obj_3geo_Vect {
  PyObject_HEAD
  struct __pyx_t_3geo_c_Vect c_value;
};


/* "/home/charlie/Work/tichy/tichy/guic/cobject.pxd":22
 * from geo cimport Vect
 * 
 * cdef class Object:             # <<<<<<<<<<<<<< 
 *     cdef void _emit(self, char* event) except *
 *     cdef void _emit_1(self, char* event, v) except *
 */

struct __pyx_vtabstruct_7cobject_Object {
  void (*_emit)(struct __pyx_obj_7cobject_Object *, char *);
  void (*_emit_1)(struct __pyx_obj_7cobject_Object *, char *, PyObject *);
};
static struct __pyx_vtabstruct_7cobject_Object *__pyx_vtabptr_7cobject_Object;


/* "/home/charlie/Work/tichy/tichy/guic/widget.pxd":30
 * # XXX: the names of the attributes are totally crazy !!!
 * 
 * cdef class Widget(Object):             # <<<<<<<<<<<<<< 
 *     cdef readonly Rect rect
 *     cdef readonly Vect _pos
 */

struct __pyx_vtabstruct_6widget_Widget {
  struct __pyx_vtabstruct_7cobject_Object __pyx_base;
  void (*c_need_organize)(struct __pyx_obj_6widget_Widget *, struct __pyx_obj_6widget_Widget *);
  void (*c_need_resize)(struct __pyx_obj_6widget_Widget *, struct __pyx_obj_6widget_Widget *);
  void (*c_draw)(struct __pyx_obj_6widget_Widget *, struct __pyx_obj_7painter_Painter *);
  void (*c_do_resize)(struct __pyx_obj_6widget_Widget *);
  void (*c_need_redraw)(struct __pyx_obj_6widget_Widget *, struct __pyx_t_3geo_c_Rect *);
};
static struct __pyx_vtabstruct_6widget_Widget *__pyx_vtabptr_6widget_Widget;


/* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":13
 * import pygame
 * 
 * cdef class SurfWidget(Widget):             # <<<<<<<<<<<<<< 
 *     def __init__(self, parent, size, **kargs):
 *         super(SurfWidget, self).__init__(parent, optimal_size = size, **kargs)
 */

struct __pyx_vtabstruct_11surf_widget_SurfWidget {
  struct __pyx_vtabstruct_6widget_Widget __pyx_base;
};
static struct __pyx_vtabstruct_11surf_widget_SurfWidget *__pyx_vtabptr_11surf_widget_SurfWidget;


/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":33
 *     c_Vect size
 * 
 * cdef class Rect:             # <<<<<<<<<<<<<< 
 *     cdef c_Rect c_value
 *     
 */

struct __pyx_vtabstruct_3geo_Rect {
  struct __pyx_obj_3geo_Rect *(*move)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Vect *);
  struct __pyx_obj_3geo_Rect *(*clip)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  struct __pyx_obj_3geo_Rect *(*merge)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  int (*intersect)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  struct __pyx_obj_3geo_Rect *(*inside)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
};
static struct __pyx_vtabstruct_3geo_Rect *__pyx_vtabptr_3geo_Rect;


/* "/home/charlie/Work/tichy/tichy/guic/painter.pxd":23
 * 
 * 
 * cdef class Painter:             # <<<<<<<<<<<<<< 
 *     """ This class is used to draw all the widgets
 *         
 */

struct __pyx_vtabstruct_7painter_Painter {
  void (*_draw)(struct __pyx_obj_7painter_Painter *, PyObject *);
  void (*c_move)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Vect *);
  void (*c_umove)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Vect *);
  void (*c_clip)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Rect *);
  void (*c_set_mask)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Rect *);
  struct __pyx_obj_7painter_Painter *(*_to_surface)(struct __pyx_obj_7painter_Painter *, PyObject *);
  PyObject *(*c_surface_from_size)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Vect *);
  PyObject *(*_surface_from_image)(struct __pyx_obj_7painter_Painter *, char *);
  PyObject *(*_surface_from_text)(struct __pyx_obj_7painter_Painter *, PyObject *, PyObject *, PyObject *, PyObject *);
  void (*_draw_surface)(struct __pyx_obj_7painter_Painter *, PyObject *, PyObject *);
  void (*_fill)(struct __pyx_obj_7painter_Painter *, PyObject *, struct __pyx_obj_3geo_Vect *);
  void (*_draw_frame)(struct __pyx_obj_7painter_Painter *, PyObject *, struct __pyx_obj_3geo_Vect *);
  void (*_flip)(struct __pyx_obj_7painter_Painter *, struct __pyx_obj_3geo_Rect *);
};
static struct __pyx_vtabstruct_7painter_Painter *__pyx_vtabptr_7painter_Painter;

static PyTypeObject *__pyx_ptype_3geo_Vect = 0;
static PyTypeObject *__pyx_ptype_3geo_Rect = 0;
static struct __pyx_obj_3geo_Vect *(*__pyx_f_3geo_c_vect_to_py)(struct __pyx_t_3geo_c_Vect *); /*proto*/
static int (*__pyx_f_3geo_c_vect_equal)(struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Vect *); /*proto*/
static struct __pyx_obj_3geo_Rect *(*__pyx_f_3geo_c_rect_to_py)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_left)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_right)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_top)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_bottom)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_width)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_height)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_contains)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_intersect)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_inside)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_merge)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_clip)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_move)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Rect *); /*proto*/

static PyTypeObject *__pyx_ptype_7cobject_Object = 0;

static PyTypeObject *__pyx_ptype_7painter_Painter = 0;

static PyTypeObject *__pyx_ptype_6widget_Widget = 0;

static PyTypeObject *__pyx_ptype_11surf_widget_SurfWidget = 0;


/* Implementation of surf_widget */


static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_pygame;

/* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":14
 * 
 * cdef class SurfWidget(Widget):
 *     def __init__(self, parent, size, **kargs):             # <<<<<<<<<<<<<< 
 *         super(SurfWidget, self).__init__(parent, optimal_size = size, **kargs)
 *         self.store_surface = True
 */

static PyObject *__pyx_int_0;
static PyObject *__pyx_int_32;

static PyObject *__pyx_n_super;
static PyObject *__pyx_n_optimal_size;
static PyObject *__pyx_n_Surface;

static PyObject *__pyx_builtin_super;


static int __pyx_pf_11surf_widget_10SurfWidget___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_11surf_widget_10SurfWidget___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_parent = 0;
  PyObject *__pyx_v_size = 0;
  PyObject *__pyx_v_kargs = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"parent","size",0};
  if (unlikely(PyTuple_GET_SIZE(__pyx_args) > 2)) {
    __Pyx_RaiseArgtupleTooLong(2, PyTuple_GET_SIZE(__pyx_args));
    return -1;
  }
  if (unlikely(__Pyx_SplitKeywords(&__pyx_kwds, __pyx_argnames, &__pyx_v_kargs, 0) < 0)) return -1;
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_parent = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_size = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_parent, &__pyx_v_size))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_kwds);
  Py_DECREF(__pyx_v_kargs);
  __Pyx_AddTraceback("surf_widget.SurfWidget.__init__");
  return -1;
  __pyx_L3:;

  /* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":15
 * cdef class SurfWidget(Widget):
 *     def __init__(self, parent, size, **kargs):
 *         super(SurfWidget, self).__init__(parent, optimal_size = size, **kargs)             # <<<<<<<<<<<<<< 
 *         self.store_surface = True
 *         self.surface = pygame.Surface(size, 0, 32)
 */
  __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(((PyObject*)__pyx_ptype_11surf_widget_SurfWidget));
  PyTuple_SET_ITEM(__pyx_1, 0, ((PyObject*)__pyx_ptype_11surf_widget_SurfWidget));
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_self);
  __pyx_2 = PyObject_Call(__pyx_builtin_super, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n___init__); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_parent);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_parent);
  __pyx_3 = PyDict_New(); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_3, __pyx_n_optimal_size, __pyx_v_size) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyDict_Update(((PyObject *)__pyx_3), __pyx_v_kargs) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyEval_CallObjectWithKeywords(__pyx_1, ((PyObject *)__pyx_2), ((PyObject *)__pyx_3)); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":16
 *     def __init__(self, parent, size, **kargs):
 *         super(SurfWidget, self).__init__(parent, optimal_size = size, **kargs)
 *         self.store_surface = True             # <<<<<<<<<<<<<< 
 *         self.surface = pygame.Surface(size, 0, 32)
 *         
 */
  ((struct __pyx_obj_11surf_widget_SurfWidget *)__pyx_v_self)->__pyx_base.store_surface = 1;

  /* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":17
 *         super(SurfWidget, self).__init__(parent, optimal_size = size, **kargs)
 *         self.store_surface = True
 *         self.surface = pygame.Surface(size, 0, 32)             # <<<<<<<<<<<<<< 
 *         
 *     cdef void c_do_resize(self):
 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_pygame); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_Surface); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyTuple_New(3); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_size);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_size);
  Py_INCREF(__pyx_int_0);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_int_0);
  Py_INCREF(__pyx_int_32);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_int_32);
  __pyx_4 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  Py_DECREF(((struct __pyx_obj_11surf_widget_SurfWidget *)__pyx_v_self)->__pyx_base.surface);
  ((struct __pyx_obj_11surf_widget_SurfWidget *)__pyx_v_self)->__pyx_base.surface = __pyx_4;
  __pyx_4 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("surf_widget.SurfWidget.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_kargs);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":19
 *         self.surface = pygame.Surface(size, 0, 32)
 *         
 *     cdef void c_do_resize(self):             # <<<<<<<<<<<<<< 
 *         pass
 *         
 */

static  void __pyx_f_11surf_widget_10SurfWidget_c_do_resize(struct __pyx_obj_11surf_widget_SurfWidget *__pyx_v_self) {

}

/* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":22
 *         pass
 *         
 *     cdef void c_need_redraw(self, c_Rect *rect):             # <<<<<<<<<<<<<< 
 *         cdef c_Rect p_rect
 *         c_rect_move(rect, &self._pos.c_value, &p_rect)
 */

static PyObject *__pyx_n_need_redraw;

static  void __pyx_f_11surf_widget_10SurfWidget_c_need_redraw(struct __pyx_obj_11surf_widget_SurfWidget *__pyx_v_self, struct __pyx_t_3geo_c_Rect *__pyx_v_rect) {
  struct __pyx_t_3geo_c_Rect __pyx_v_p_rect;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":24
 *     cdef void c_need_redraw(self, c_Rect *rect):
 *         cdef c_Rect p_rect
 *         c_rect_move(rect, &self._pos.c_value, &p_rect)             # <<<<<<<<<<<<<< 
 *         if self.parent is not None:
 *             self.parent.need_redraw(c_rect_to_py(&p_rect)) # XXX: super slow !!! Need to make screen cython
 */
  __pyx_f_3geo_c_rect_move(__pyx_v_rect, (&__pyx_v_self->__pyx_base._pos->c_value), (&__pyx_v_p_rect));

  /* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":25
 *         cdef c_Rect p_rect
 *         c_rect_move(rect, &self._pos.c_value, &p_rect)
 *         if self.parent is not None:             # <<<<<<<<<<<<<< 
 *             self.parent.need_redraw(c_rect_to_py(&p_rect)) # XXX: super slow !!! Need to make screen cython
 */
  __pyx_1 = (((PyObject *)__pyx_v_self->__pyx_base.parent) != Py_None);
  if (__pyx_1) {

    /* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":26
 *         c_rect_move(rect, &self._pos.c_value, &p_rect)
 *         if self.parent is not None:
 *             self.parent.need_redraw(c_rect_to_py(&p_rect)) # XXX: super slow !!! Need to make screen cython             # <<<<<<<<<<<<<< 
 */
    __pyx_2 = PyObject_GetAttr(((PyObject *)__pyx_v_self->__pyx_base.parent), __pyx_n_need_redraw); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_3 = ((PyObject *)__pyx_f_3geo_c_rect_to_py((&__pyx_v_p_rect))); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("surf_widget.SurfWidget.c_need_redraw");
  __pyx_L0:;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Surface, "Surface"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n_need_redraw, "need_redraw"},
  {&__pyx_n_optimal_size, "optimal_size"},
  {&__pyx_n_pygame, "pygame"},
  {&__pyx_n_super, "super"},
  {0, 0}
};
static struct __pyx_vtabstruct_11surf_widget_SurfWidget __pyx_vtable_11surf_widget_SurfWidget;

static PyObject *__pyx_tp_new_11surf_widget_SurfWidget(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_11surf_widget_SurfWidget *p;
  PyObject *o = __pyx_ptype_6widget_Widget->tp_new(t, a, k);
  if (!o) return 0;
  p = ((struct __pyx_obj_11surf_widget_SurfWidget *)o);
  *(struct __pyx_vtabstruct_11surf_widget_SurfWidget **)&p->__pyx_base.__pyx_base.__pyx_vtab = __pyx_vtabptr_11surf_widget_SurfWidget;
  return o;
}

static void __pyx_tp_dealloc_11surf_widget_SurfWidget(PyObject *o) {
  __pyx_ptype_6widget_Widget->tp_dealloc(o);
}

static int __pyx_tp_traverse_11surf_widget_SurfWidget(PyObject *o, visitproc v, void *a) {
  int e;
  if (__pyx_ptype_6widget_Widget->tp_traverse) {
    e = __pyx_ptype_6widget_Widget->tp_traverse(o, v, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_11surf_widget_SurfWidget(PyObject *o) {
  if (__pyx_ptype_6widget_Widget->tp_clear) {
    __pyx_ptype_6widget_Widget->tp_clear(o);
  }
  return 0;
}

static struct PyMethodDef __pyx_methods_11surf_widget_SurfWidget[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_SurfWidget = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_SurfWidget = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_SurfWidget = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_SurfWidget = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_11surf_widget_SurfWidget = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "surf_widget.SurfWidget", /*tp_name*/
  sizeof(struct __pyx_obj_11surf_widget_SurfWidget), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_11surf_widget_SurfWidget, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_SurfWidget, /*tp_as_number*/
  &__pyx_tp_as_sequence_SurfWidget, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_SurfWidget, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_SurfWidget, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_11surf_widget_SurfWidget, /*tp_traverse*/
  __pyx_tp_clear_11surf_widget_SurfWidget, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_11surf_widget_SurfWidget, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_11surf_widget_10SurfWidget___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_11surf_widget_SurfWidget, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initsurf_widget(void); /*proto*/
PyMODINIT_FUNC initsurf_widget(void) {
  PyObject *__pyx_1 = 0;
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("surf_widget", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  __pyx_int_0 = PyInt_FromLong(0); if (unlikely(!__pyx_int_0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_32 = PyInt_FromLong(32); if (unlikely(!__pyx_int_32)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- String init code ---*/
  /*--- Builtin init code ---*/
  __pyx_builtin_super = __Pyx_GetName(__pyx_b, __pyx_n_super); if (!__pyx_builtin_super) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_ptype_6widget_Widget = __Pyx_ImportType("widget", "Widget", sizeof(struct __pyx_obj_6widget_Widget)); if (unlikely(!__pyx_ptype_6widget_Widget)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_6widget_Widget->tp_dict, &__pyx_vtabptr_6widget_Widget) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_vtabptr_11surf_widget_SurfWidget = &__pyx_vtable_11surf_widget_SurfWidget;
  __pyx_vtable_11surf_widget_SurfWidget.__pyx_base = *__pyx_vtabptr_6widget_Widget;
  *(void(**)(void))&__pyx_vtable_11surf_widget_SurfWidget.__pyx_base.c_do_resize = (void(*)(void))__pyx_f_11surf_widget_10SurfWidget_c_do_resize;
  *(void(**)(void))&__pyx_vtable_11surf_widget_SurfWidget.__pyx_base.c_need_redraw = (void(*)(void))__pyx_f_11surf_widget_10SurfWidget_c_need_redraw;
  __pyx_type_11surf_widget_SurfWidget.tp_base = __pyx_ptype_6widget_Widget;
  if (PyType_Ready(&__pyx_type_11surf_widget_SurfWidget) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_11surf_widget_SurfWidget.tp_dict, __pyx_vtabptr_11surf_widget_SurfWidget) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "SurfWidget", (PyObject *)&__pyx_type_11surf_widget_SurfWidget) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_11surf_widget_SurfWidget = &__pyx_type_11surf_widget_SurfWidget;
  /*--- Type import code ---*/
  __pyx_ptype_3geo_Vect = __Pyx_ImportType("geo", "Vect", sizeof(struct __pyx_obj_3geo_Vect)); if (unlikely(!__pyx_ptype_3geo_Vect)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_3geo_Rect = __Pyx_ImportType("geo", "Rect", sizeof(struct __pyx_obj_3geo_Rect)); if (unlikely(!__pyx_ptype_3geo_Rect)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_3geo_Rect->tp_dict, &__pyx_vtabptr_3geo_Rect) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_7cobject_Object = __Pyx_ImportType("cobject", "Object", sizeof(struct __pyx_obj_7cobject_Object)); if (unlikely(!__pyx_ptype_7cobject_Object)) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_7cobject_Object->tp_dict, &__pyx_vtabptr_7cobject_Object) < 0) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_7painter_Painter = __Pyx_ImportType("painter", "Painter", sizeof(struct __pyx_obj_7painter_Painter)); if (unlikely(!__pyx_ptype_7painter_Painter)) {__pyx_filename = __pyx_f[3]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_7painter_Painter->tp_dict, &__pyx_vtabptr_7painter_Painter) < 0) {__pyx_filename = __pyx_f[3]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  /*--- Function import code ---*/
  __pyx_1 = __Pyx_ImportModule("geo"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_vect_to_py", (void**)&__pyx_f_3geo_c_vect_to_py, "struct __pyx_obj_3geo_Vect *(struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_vect_equal", (void**)&__pyx_f_3geo_c_vect_equal, "int (struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_to_py", (void**)&__pyx_f_3geo_c_rect_to_py, "struct __pyx_obj_3geo_Rect *(struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_left", (void**)&__pyx_f_3geo_c_rect_left, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_right", (void**)&__pyx_f_3geo_c_rect_right, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_top", (void**)&__pyx_f_3geo_c_rect_top, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_bottom", (void**)&__pyx_f_3geo_c_rect_bottom, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_width", (void**)&__pyx_f_3geo_c_rect_width, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_height", (void**)&__pyx_f_3geo_c_rect_height, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_contains", (void**)&__pyx_f_3geo_c_rect_contains, "int (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_intersect", (void**)&__pyx_f_3geo_c_rect_intersect, "int (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_inside", (void**)&__pyx_f_3geo_c_rect_inside, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_merge", (void**)&__pyx_f_3geo_c_rect_merge, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_clip", (void**)&__pyx_f_3geo_c_rect_clip, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_move", (void**)&__pyx_f_3geo_c_rect_move, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  /*--- Execution code ---*/

  /* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":11
 * from painter cimport Painter
 * 
 * import pygame             # <<<<<<<<<<<<<< 
 * 
 * cdef class SurfWidget(Widget):
 */
  __pyx_1 = __Pyx_Import(__pyx_n_pygame, 0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_pygame, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/surf_widget.pyx":22
 *         pass
 *         
 *     cdef void c_need_redraw(self, c_Rect *rect):             # <<<<<<<<<<<<<< 
 *         cdef c_Rect p_rect
 *         c_rect_move(rect, &self._pos.c_value, &p_rect)
 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("surf_widget");
}

static char *__pyx_filenames[] = {
  "surf_widget.pyx",
  "geo.pxd",
  "cobject.pxd",
  "painter.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static int __Pyx_SplitKeywords(
    PyObject **kwds,
    char *kwd_list[], 
    PyObject **kwds2,
    char rqd_kwds[])
{
    PyObject *s = 0, *x = 0, *kwds1 = 0;
    int i;
    char **p;
    
    if (*kwds) {
        kwds1 = PyDict_New();
        if (!kwds1)
            goto bad;
        *kwds2 = PyDict_Copy(*kwds);
        if (!*kwds2)
            goto bad;
        for (i = 0, p = kwd_list; *p; i++, p++) {
            s = PyString_FromString(*p);
            x = PyDict_GetItem(*kwds, s);
            if (x) {
                if (PyDict_SetItem(kwds1, s, x) < 0)
                    goto bad;
                if (PyDict_DelItem(*kwds2, s) < 0)
                    goto bad;
            }
            else if (rqd_kwds && rqd_kwds[i])
                goto missing_kwarg;
            Py_DECREF(s);
        }
        s = 0;
    }
    else {
        if (rqd_kwds) {
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i])
                    goto missing_kwarg;
        }
        *kwds2 = PyDict_New();
        if (!*kwds2)
            goto bad;
    }

    *kwds = kwds1;
    return 0;
missing_kwarg:
    PyErr_Format(PyExc_TypeError,
        "required keyword argument '%s' is missing", *p);
bad:
    Py_XDECREF(s);
    Py_XDECREF(kwds1);
    Py_XDECREF(*kwds2);
    return -1;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;
    
    py_name = PyString_FromString(module_name);
    if (!py_name)
        goto bad;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_name);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;
    
    py_name = PyString_FromString(name);
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr) {
    int result;
    PyObject *pycobj;
    
    pycobj = PyMapping_GetItemString(dict, "__pyx_vtable__");
    if (!pycobj)
        goto bad;
    *(void **)vtabptr = PyCObject_AsVoidPtr(pycobj);
    if (!*(void **)vtabptr)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    char *desc;
    
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%s does not export expected C function %s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    desc = (char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    if (strcmp(desc, sig) != 0) {
        PyErr_Format(PyExc_TypeError,
            "C function %s.%s has wrong signature (expected %s, got %s)",
                PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    *f = PyCObject_AsVoidPtr(cobj);
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
    }
    else {
        py_funcname = PyString_FromString(funcname);
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
