/* Generated by Cython 0.9.6.14 on Thu Nov 20 15:27:13 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static char * __pyx_cfilenm= __FILE__;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name, int exact); /*proto*/

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static int __Pyx_SplitKeywords(PyObject **kwds, char *kwd_list[],     PyObject **kwds2, char rqd_kwds[]); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_UnpackItem(PyObject *, Py_ssize_t index); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations */

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":19
 * #    along with Tichy.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * cdef struct c_Vect:             # <<<<<<<<<<<<<< 
 *     int x
 *     int y
 */

struct __pyx_t_3geo_c_Vect {
  int x;
  int y;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":29
 * cdef inline int c_vect_equal(c_Vect* v1, c_Vect* v2)
 * 
 * cdef struct c_Rect:             # <<<<<<<<<<<<<< 
 *     c_Vect pos
 *     c_Vect size
 */

struct __pyx_t_3geo_c_Rect {
  struct __pyx_t_3geo_c_Vect pos;
  struct __pyx_t_3geo_c_Vect size;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":33
 *     c_Vect size
 * 
 * cdef class Rect:             # <<<<<<<<<<<<<< 
 *     cdef c_Rect c_value
 *     
 */

struct __pyx_obj_3geo_Rect {
  PyObject_HEAD
  struct __pyx_vtabstruct_3geo_Rect *__pyx_vtab;
  struct __pyx_t_3geo_c_Rect c_value;
};

/* "/home/charlie/Work/tichy/tichy/guic/painter.pxd":23
 * 
 * 
 * cdef class Painter:             # <<<<<<<<<<<<<< 
 *     """ This class is used to draw all the widgets
 *         
 */

struct __pyx_obj_7painter_Painter {
  PyObject_HEAD
  struct __pyx_vtabstruct_7painter_Painter *__pyx_vtab;
  struct __pyx_t_3geo_c_Vect c_pos;
  struct __pyx_t_3geo_c_Rect c_mask;
};

/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":23
 *     int y
 * 
 * cdef class Vect:             # <<<<<<<<<<<<<< 
 *     cdef c_Vect c_value
 *     
 */

struct __pyx_obj_3geo_Vect {
  PyObject_HEAD
  struct __pyx_t_3geo_c_Vect c_value;
};

/* "/home/charlie/Work/tichy/tichy/guic/cobject.pxd":22
 * from geo cimport Vect
 * 
 * cdef class Object:             # <<<<<<<<<<<<<< 
 *     cdef void _emit(self, char* event) except *
 *     cdef void _emit_1(self, char* event, v) except *
 */

struct __pyx_obj_7cobject_Object {
  PyObject_HEAD
  struct __pyx_vtabstruct_7cobject_Object *__pyx_vtab;
  PyObject *__listeners;
};

/* "/home/charlie/Work/tichy/tichy/guic/widget.pxd":30
 * # XXX: the names of the attributes are totally crazy !!!
 * 
 * cdef class Widget(Object):             # <<<<<<<<<<<<<< 
 *     cdef readonly Rect rect
 *     cdef readonly Vect _pos
 */

struct __pyx_obj_6widget_Widget {
  struct __pyx_obj_7cobject_Object __pyx_base;
  struct __pyx_obj_3geo_Rect *rect;
  struct __pyx_obj_3geo_Vect *_pos;
  struct __pyx_obj_6widget_Widget *parent;
  PyObject *item;
  PyObject *tags;
  PyObject *surface;
  int store_surface;
  PyObject *_style;
  PyObject *style_dict;
  struct __pyx_obj_3geo_Vect *_optimal_size;
  int fixed_optimal_size;
  struct __pyx_obj_3geo_Vect *_min_size;
  int fixed_min_size;
  int expand;
  int _organized;
  int _resized;
  int resizable;
  int _destroyed;
  PyObject *children;
  struct __pyx_obj_6widget_Widget *focused;
  int clickable;
};

/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":32
 * from geo cimport Vect
 * 
 * cdef class Window(Widget):             # <<<<<<<<<<<<<< 
 *     """ Special widget that can receive events from an external source
 *         
 */

struct __pyx_obj_6window_Window {
  struct __pyx_obj_6widget_Widget __pyx_base;
  PyObject *events;
  PyObject *events_source;
  struct __pyx_obj_6window_Window *modal_child;
  int modal;
  int child_need_organize;
  int child_need_resize;
};


/* "/home/charlie/Work/tichy/tichy/guic/cobject.pxd":22
 * from geo cimport Vect
 * 
 * cdef class Object:             # <<<<<<<<<<<<<< 
 *     cdef void _emit(self, char* event) except *
 *     cdef void _emit_1(self, char* event, v) except *
 */

struct __pyx_vtabstruct_7cobject_Object {
  void (*_emit)(struct __pyx_obj_7cobject_Object *, char *);
  void (*_emit_1)(struct __pyx_obj_7cobject_Object *, char *, PyObject *);
};
static struct __pyx_vtabstruct_7cobject_Object *__pyx_vtabptr_7cobject_Object;


/* "/home/charlie/Work/tichy/tichy/guic/geo.pxd":33
 *     c_Vect size
 * 
 * cdef class Rect:             # <<<<<<<<<<<<<< 
 *     cdef c_Rect c_value
 *     
 */

struct __pyx_vtabstruct_3geo_Rect {
  struct __pyx_obj_3geo_Rect *(*move)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Vect *);
  struct __pyx_obj_3geo_Rect *(*clip)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  struct __pyx_obj_3geo_Rect *(*merge)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  int (*intersect)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
  struct __pyx_obj_3geo_Rect *(*inside)(struct __pyx_obj_3geo_Rect *, struct __pyx_obj_3geo_Rect *);
};
static struct __pyx_vtabstruct_3geo_Rect *__pyx_vtabptr_3geo_Rect;


/* "/home/charlie/Work/tichy/tichy/guic/widget.pxd":30
 * # XXX: the names of the attributes are totally crazy !!!
 * 
 * cdef class Widget(Object):             # <<<<<<<<<<<<<< 
 *     cdef readonly Rect rect
 *     cdef readonly Vect _pos
 */

struct __pyx_vtabstruct_6widget_Widget {
  struct __pyx_vtabstruct_7cobject_Object __pyx_base;
  void (*c_need_organize)(struct __pyx_obj_6widget_Widget *, struct __pyx_obj_6widget_Widget *);
  void (*c_need_resize)(struct __pyx_obj_6widget_Widget *, struct __pyx_obj_6widget_Widget *);
  void (*c_draw)(struct __pyx_obj_6widget_Widget *, struct __pyx_obj_7painter_Painter *);
  void (*c_do_resize)(struct __pyx_obj_6widget_Widget *);
  void (*c_need_redraw)(struct __pyx_obj_6widget_Widget *, struct __pyx_t_3geo_c_Rect *);
};
static struct __pyx_vtabstruct_6widget_Widget *__pyx_vtabptr_6widget_Widget;


/* "/home/charlie/Work/tichy/tichy/guic/painter.pxd":23
 * 
 * 
 * cdef class Painter:             # <<<<<<<<<<<<<< 
 *     """ This class is used to draw all the widgets
 *         
 */

struct __pyx_vtabstruct_7painter_Painter {
  void (*_draw)(struct __pyx_obj_7painter_Painter *, PyObject *);
  void (*c_move)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Vect *);
  void (*c_umove)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Vect *);
  void (*c_clip)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Rect *);
  void (*c_set_mask)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Rect *);
  struct __pyx_obj_7painter_Painter *(*_to_surface)(struct __pyx_obj_7painter_Painter *, PyObject *);
  PyObject *(*c_surface_from_size)(struct __pyx_obj_7painter_Painter *, struct __pyx_t_3geo_c_Vect *);
  PyObject *(*_surface_from_image)(struct __pyx_obj_7painter_Painter *, char *);
  PyObject *(*_surface_from_text)(struct __pyx_obj_7painter_Painter *, PyObject *, PyObject *, PyObject *, PyObject *);
  void (*_draw_surface)(struct __pyx_obj_7painter_Painter *, PyObject *, PyObject *);
  void (*_fill)(struct __pyx_obj_7painter_Painter *, PyObject *, struct __pyx_obj_3geo_Vect *);
  void (*_draw_frame)(struct __pyx_obj_7painter_Painter *, PyObject *, struct __pyx_obj_3geo_Vect *);
  void (*_flip)(struct __pyx_obj_7painter_Painter *, struct __pyx_obj_3geo_Rect *);
};
static struct __pyx_vtabstruct_7painter_Painter *__pyx_vtabptr_7painter_Painter;


/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":32
 * from geo cimport Vect
 * 
 * cdef class Window(Widget):             # <<<<<<<<<<<<<< 
 *     """ Special widget that can receive events from an external source
 *         
 */

struct __pyx_vtabstruct_6window_Window {
  struct __pyx_vtabstruct_6widget_Widget __pyx_base;
};
static struct __pyx_vtabstruct_6window_Window *__pyx_vtabptr_6window_Window;

static PyTypeObject *__pyx_ptype_3geo_Vect = 0;
static PyTypeObject *__pyx_ptype_3geo_Rect = 0;
static struct __pyx_obj_3geo_Vect *(*__pyx_f_3geo_c_vect_to_py)(struct __pyx_t_3geo_c_Vect *); /*proto*/
static int (*__pyx_f_3geo_c_vect_equal)(struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Vect *); /*proto*/
static struct __pyx_obj_3geo_Rect *(*__pyx_f_3geo_c_rect_to_py)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_left)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_right)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_top)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_bottom)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_width)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_height)(struct __pyx_t_3geo_c_Rect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_contains)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *); /*proto*/
static int (*__pyx_f_3geo_c_rect_intersect)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_inside)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_merge)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_clip)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *); /*proto*/
static void (*__pyx_f_3geo_c_rect_move)(struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Rect *); /*proto*/

static PyTypeObject *__pyx_ptype_7cobject_Object = 0;

static PyTypeObject *__pyx_ptype_7painter_Painter = 0;

static PyTypeObject *__pyx_ptype_6widget_Widget = 0;

static PyTypeObject *__pyx_ptype_6window_Window = 0;


/* Implementation of window */

static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_remove;
static PyObject *__pyx_n_resize;
static PyObject *__pyx_n_sorted_children;
static PyObject *__pyx_n_need_organize;
static PyObject *__pyx_n_need_resize;
static PyObject *__pyx_n_tick;

/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":47
 *     cdef int child_need_resize
 * 
 *     def __init__(self, Widget parent, modal = True, events_source = None, **kargs):             # <<<<<<<<<<<<<< 
 *         Widget.__init__(self, parent, **kargs)
 *         
 */

static PyObject *__pyx_n_window;

static int __pyx_pf_6window_6Window___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_6window_6Window___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_6widget_Widget *__pyx_v_parent = 0;
  PyObject *__pyx_v_modal = 0;
  PyObject *__pyx_v_events_source = 0;
  PyObject *__pyx_v_kargs = 0;
  struct __pyx_obj_6window_Window *__pyx_v_source;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  int __pyx_5;
  static char *__pyx_argnames[] = {"parent","modal","events_source",0};
  __pyx_v_modal = Py_True;
  __pyx_v_events_source = Py_None;
  if (unlikely(PyTuple_GET_SIZE(__pyx_args) > 3)) {
    __Pyx_RaiseArgtupleTooLong(3, PyTuple_GET_SIZE(__pyx_args));
    return -1;
  }
  if (unlikely(__Pyx_SplitKeywords(&__pyx_kwds, __pyx_argnames, &__pyx_v_kargs, 0) < 0)) return -1;
  if (likely(!__pyx_kwds) && likely(1 <= PyTuple_GET_SIZE(__pyx_args)) && likely(PyTuple_GET_SIZE(__pyx_args) <= 3)) {
    __pyx_v_parent = ((struct __pyx_obj_6widget_Widget *)PyTuple_GET_ITEM(__pyx_args, 0));
    if (PyTuple_GET_SIZE(__pyx_args) > 1) {
      __pyx_v_modal = PyTuple_GET_ITEM(__pyx_args, 1);
      if (PyTuple_GET_SIZE(__pyx_args) > 2) {
        __pyx_v_events_source = PyTuple_GET_ITEM(__pyx_args, 2);
      }
    }
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|OO", __pyx_argnames, &__pyx_v_parent, &__pyx_v_modal, &__pyx_v_events_source))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_kwds);
  Py_DECREF(__pyx_v_kargs);
  __Pyx_AddTraceback("window.Window.__init__");
  return -1;
  __pyx_L3:;
  Py_INCREF(__pyx_v_events_source);
  __pyx_v_source = ((struct __pyx_obj_6window_Window *)Py_None); Py_INCREF(Py_None);
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_parent), __pyx_ptype_6widget_Widget, 1, "parent", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":48
 * 
 *     def __init__(self, Widget parent, modal = True, events_source = None, **kargs):
 *         Widget.__init__(self, parent, **kargs)             # <<<<<<<<<<<<<< 
 *         
 *         if events_source is None:
 */
  __pyx_1 = PyObject_GetAttr(((PyObject*)__pyx_ptype_6widget_Widget), __pyx_n___init__); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_self);
  Py_INCREF(((PyObject *)__pyx_v_parent));
  PyTuple_SET_ITEM(__pyx_2, 1, ((PyObject *)__pyx_v_parent));
  __pyx_3 = PyEval_CallObjectWithKeywords(__pyx_1, ((PyObject *)__pyx_2), __pyx_v_kargs); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":50
 *         Widget.__init__(self, parent, **kargs)
 *         
 *         if events_source is None:             # <<<<<<<<<<<<<< 
 *             events_source = parent if isinstance(parent, Window) else parent.window
 *             
 */
  __pyx_4 = (__pyx_v_events_source == Py_None);
  if (__pyx_4) {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":51
 *         
 *         if events_source is None:
 *             events_source = parent if isinstance(parent, Window) else parent.window             # <<<<<<<<<<<<<< 
 *             
 *         self.events_source = events_source
 */
    __pyx_4 = PyObject_IsInstance(((PyObject *)__pyx_v_parent), ((PyObject*)__pyx_ptype_6window_Window)); if (unlikely(__pyx_4 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
    if (__pyx_4) {
      __pyx_1 = ((PyObject *)__pyx_v_parent);
      Py_INCREF(__pyx_1);
      } else {
      __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_parent), __pyx_n_window); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1;}
    }
    Py_DECREF(__pyx_v_events_source);
    __pyx_v_events_source = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":53
 *             events_source = parent if isinstance(parent, Window) else parent.window
 *             
 *         self.events_source = events_source             # <<<<<<<<<<<<<< 
 *         self.modal_child = None
 * 
 */
  Py_INCREF(__pyx_v_events_source);
  Py_DECREF(((struct __pyx_obj_6window_Window *)__pyx_v_self)->events_source);
  ((struct __pyx_obj_6window_Window *)__pyx_v_self)->events_source = __pyx_v_events_source;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":54
 *             
 *         self.events_source = events_source
 *         self.modal_child = None             # <<<<<<<<<<<<<< 
 * 
 *         cdef Window source
 */
  Py_INCREF(Py_None);
  Py_DECREF(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child));
  ((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child = ((struct __pyx_obj_6window_Window *)Py_None);

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":57
 * 
 *         cdef Window source
 *         if modal and isinstance(self.events_source, Window):             # <<<<<<<<<<<<<< 
 *             source = self.events_source
 *             source.modal_child = self
 */
  __pyx_2 = __pyx_v_modal;
  Py_INCREF(__pyx_2);
  __pyx_5 = __Pyx_PyObject_IsTrue(__pyx_2); if (unlikely(__pyx_5 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__pyx_5) {
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_5 = PyObject_IsInstance(((struct __pyx_obj_6window_Window *)__pyx_v_self)->events_source, ((PyObject*)__pyx_ptype_6window_Window)); if (unlikely(__pyx_5 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_2 = __Pyx_PyBool_FromLong(__pyx_5); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
  }
  __pyx_5 = __Pyx_PyObject_IsTrue(__pyx_2); if (unlikely(__pyx_5 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_5) {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":58
 *         cdef Window source
 *         if modal and isinstance(self.events_source, Window):
 *             source = self.events_source             # <<<<<<<<<<<<<< 
 *             source.modal_child = self
 *             
 */
    if (!(__Pyx_TypeTest(((struct __pyx_obj_6window_Window *)__pyx_v_self)->events_source, __pyx_ptype_6window_Window))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_INCREF(((struct __pyx_obj_6window_Window *)__pyx_v_self)->events_source);
    Py_DECREF(((PyObject *)__pyx_v_source));
    __pyx_v_source = ((struct __pyx_obj_6window_Window *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->events_source);

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":59
 *         if modal and isinstance(self.events_source, Window):
 *             source = self.events_source
 *             source.modal_child = self             # <<<<<<<<<<<<<< 
 *             
 *         self.child_need_organize = False
 */
    Py_INCREF(__pyx_v_self);
    Py_DECREF(((PyObject *)__pyx_v_source->modal_child));
    __pyx_v_source->modal_child = ((struct __pyx_obj_6window_Window *)__pyx_v_self);
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":61
 *             source.modal_child = self
 *             
 *         self.child_need_organize = False             # <<<<<<<<<<<<<< 
 *         self.child_need_resize = False
 * 
 */
  ((struct __pyx_obj_6window_Window *)__pyx_v_self)->child_need_organize = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":62
 *             
 *         self.child_need_organize = False
 *         self.child_need_resize = False             # <<<<<<<<<<<<<< 
 * 
 *     def remove(self, Widget w):
 */
  ((struct __pyx_obj_6window_Window *)__pyx_v_self)->child_need_resize = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("window.Window.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_kargs);
  Py_DECREF((PyObject *)__pyx_v_source);
  Py_DECREF(__pyx_v_events_source);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":64
 *         self.child_need_resize = False
 * 
 *     def remove(self, Widget w):             # <<<<<<<<<<<<<< 
 *         super(Window, self).remove(w)
 *         if w is self.modal_child:
 */

static PyObject *__pyx_n_super;

static PyObject *__pyx_builtin_super;

static PyObject *__pyx_pf_6window_6Window_remove(PyObject *__pyx_v_self, PyObject *__pyx_v_w); /*proto*/
static PyObject *__pyx_pf_6window_6Window_remove(PyObject *__pyx_v_self, PyObject *__pyx_v_w) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_w), __pyx_ptype_6widget_Widget, 1, "w", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1;}

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":65
 * 
 *     def remove(self, Widget w):
 *         super(Window, self).remove(w)             # <<<<<<<<<<<<<< 
 *         if w is self.modal_child:
 *             self.modal_child = None
 */
  __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(((PyObject*)__pyx_ptype_6window_Window));
  PyTuple_SET_ITEM(__pyx_1, 0, ((PyObject*)__pyx_ptype_6window_Window));
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_self);
  __pyx_2 = PyObject_Call(__pyx_builtin_super, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_remove); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_w);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_w);
  __pyx_3 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":66
 *     def remove(self, Widget w):
 *         super(Window, self).remove(w)
 *         if w is self.modal_child:             # <<<<<<<<<<<<<< 
 *             self.modal_child = None
 *             
 */
  __pyx_4 = (__pyx_v_w == ((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child));
  if (__pyx_4) {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":67
 *         super(Window, self).remove(w)
 *         if w is self.modal_child:
 *             self.modal_child = None             # <<<<<<<<<<<<<< 
 *             
 *     def resize(self):
 */
    Py_INCREF(Py_None);
    Py_DECREF(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child));
    ((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child = ((struct __pyx_obj_6window_Window *)Py_None);
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("window.Window.remove");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":69
 *             self.modal_child = None
 *             
 *     def resize(self):             # <<<<<<<<<<<<<< 
 *         return
 *         
 */

static PyObject *__pyx_pf_6window_6Window_resize(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_6window_6Window_resize(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_r;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":70
 *             
 *     def resize(self):
 *         return             # <<<<<<<<<<<<<< 
 *         
 *     def sorted_children(self):
 */
  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":72
 *         return
 *         
 *     def sorted_children(self):             # <<<<<<<<<<<<<< 
 *         if self.modal_child:
 *             return [self.modal_child]
 */

static PyObject *__pyx_n_reversed;

static PyObject *__pyx_builtin_reversed;

static PyObject *__pyx_pf_6window_6Window_sorted_children(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_6window_6Window_sorted_children(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":73
 *         
 *     def sorted_children(self):
 *         if self.modal_child:             # <<<<<<<<<<<<<< 
 *             return [self.modal_child]
 *         return list(reversed(self.children))
 */
  __pyx_1 = __Pyx_PyObject_IsTrue(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child)); if (unlikely(__pyx_1 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__pyx_1) {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":74
 *     def sorted_children(self):
 *         if self.modal_child:
 *             return [self.modal_child]             # <<<<<<<<<<<<<< 
 *         return list(reversed(self.children))
 *         
 */
    __pyx_2 = PyList_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_INCREF(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child));
    PyList_SET_ITEM(__pyx_2, 0, ((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child));
    __pyx_r = ((PyObject *)__pyx_2);
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":75
 *         if self.modal_child:
 *             return [self.modal_child]
 *         return list(reversed(self.children))             # <<<<<<<<<<<<<< 
 *         
 *     cdef void c_draw(self, Painter painter):
 */
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->__pyx_base.children));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->__pyx_base.children));
  __pyx_3 = PyObject_Call(__pyx_builtin_reversed, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_Call(((PyObject*)&PyList_Type), ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("window.Window.sorted_children");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":77
 *         return list(reversed(self.children))
 *         
 *     cdef void c_draw(self, Painter painter):             # <<<<<<<<<<<<<< 
 *         if self.modal_child is None:
 *             Widget.c_draw(self, painter)
 */

static  void __pyx_f_6window_6Window_c_draw(struct __pyx_obj_6window_Window *__pyx_v_self, struct __pyx_obj_7painter_Painter *__pyx_v_painter) {
  int __pyx_1;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":78
 *         
 *     cdef void c_draw(self, Painter painter):
 *         if self.modal_child is None:             # <<<<<<<<<<<<<< 
 *             Widget.c_draw(self, painter)
 *         else:
 */
  __pyx_1 = (((PyObject *)__pyx_v_self->modal_child) == Py_None);
  if (__pyx_1) {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":79
 *     cdef void c_draw(self, Painter painter):
 *         if self.modal_child is None:
 *             Widget.c_draw(self, painter)             # <<<<<<<<<<<<<< 
 *         else:
 *             painter.c_move(&self.modal_child._pos.c_value)
 */
    __pyx_vtabptr_6widget_Widget->c_draw(((struct __pyx_obj_6widget_Widget *)__pyx_v_self), __pyx_v_painter); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1;}
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":81
 *             Widget.c_draw(self, painter)
 *         else:
 *             painter.c_move(&self.modal_child._pos.c_value)             # <<<<<<<<<<<<<< 
 *             self.modal_child.c_draw(painter)
 *             painter.c_umove(&self.modal_child._pos.c_value)
 */
    ((struct __pyx_vtabstruct_7painter_Painter *)__pyx_v_painter->__pyx_vtab)->c_move(__pyx_v_painter, (&__pyx_v_self->modal_child->__pyx_base._pos->c_value));

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":82
 *         else:
 *             painter.c_move(&self.modal_child._pos.c_value)
 *             self.modal_child.c_draw(painter)             # <<<<<<<<<<<<<< 
 *             painter.c_umove(&self.modal_child._pos.c_value)
 *             
 */
    ((struct __pyx_vtabstruct_6window_Window *)__pyx_v_self->modal_child->__pyx_base.__pyx_base.__pyx_vtab)->__pyx_base.c_draw(((struct __pyx_obj_6widget_Widget *)__pyx_v_self->modal_child), __pyx_v_painter); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1;}

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":83
 *             painter.c_move(&self.modal_child._pos.c_value)
 *             self.modal_child.c_draw(painter)
 *             painter.c_umove(&self.modal_child._pos.c_value)             # <<<<<<<<<<<<<< 
 *             
 *     def need_organize(self, child):
 */
    ((struct __pyx_vtabstruct_7painter_Painter *)__pyx_v_painter->__pyx_vtab)->c_umove(__pyx_v_painter, (&__pyx_v_self->modal_child->__pyx_base._pos->c_value));
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("window.Window.c_draw");
  __pyx_L0:;
}

/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":85
 *             painter.c_umove(&self.modal_child._pos.c_value)
 *             
 *     def need_organize(self, child):             # <<<<<<<<<<<<<< 
 *         self.child_need_organize = True
 *     def need_resize(self, child):
 */

static PyObject *__pyx_pf_6window_6Window_need_organize(PyObject *__pyx_v_self, PyObject *__pyx_v_child); /*proto*/
static PyObject *__pyx_pf_6window_6Window_need_organize(PyObject *__pyx_v_self, PyObject *__pyx_v_child) {
  PyObject *__pyx_r;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":86
 *             
 *     def need_organize(self, child):
 *         self.child_need_organize = True             # <<<<<<<<<<<<<< 
 *     def need_resize(self, child):
 *         self.child_need_resize = True
 */
  ((struct __pyx_obj_6window_Window *)__pyx_v_self)->child_need_organize = 1;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":87
 *     def need_organize(self, child):
 *         self.child_need_organize = True
 *     def need_resize(self, child):             # <<<<<<<<<<<<<< 
 *         self.child_need_resize = True
 *             
 */

static PyObject *__pyx_pf_6window_6Window_need_resize(PyObject *__pyx_v_self, PyObject *__pyx_v_child); /*proto*/
static PyObject *__pyx_pf_6window_6Window_need_resize(PyObject *__pyx_v_self, PyObject *__pyx_v_child) {
  PyObject *__pyx_r;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":88
 *         self.child_need_organize = True
 *     def need_resize(self, child):
 *         self.child_need_resize = True             # <<<<<<<<<<<<<< 
 *             
 *     def tick(self):
 */
  ((struct __pyx_obj_6window_Window *)__pyx_v_self)->child_need_resize = 1;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

/* "/home/charlie/Work/tichy/tichy/guic/window.pyx":90
 *         self.child_need_resize = True
 *             
 *     def tick(self):             # <<<<<<<<<<<<<< 
 *         if self.child_need_resize:
 *             self.do_resize()
 */

static PyObject *__pyx_n_do_resize;
static PyObject *__pyx_n_do_organize;
static PyObject *__pyx_n_events;
static PyObject *__pyx_n_mouse_down;
static PyObject *__pyx_n_mouse_up;
static PyObject *__pyx_n_mouse_motion;
static PyObject *__pyx_n_key_down;
static PyObject *__pyx_n_resized;
static PyObject *__pyx_n_size;

static PyObject *__pyx_k_1p;
static PyObject *__pyx_k_2p;
static PyObject *__pyx_k_3p;
static PyObject *__pyx_k_4p;

static char __pyx_k_1[] = "mouse-down";
static char __pyx_k_2[] = "mouse-up";
static char __pyx_k_3[] = "mouse-motion";
static char __pyx_k_4[] = "key-down";
static char __pyx_k_6[] = "tick";

static PyObject *__pyx_pf_6window_6Window_tick(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_6window_6Window_tick(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_v_e;
  PyObject *__pyx_v_v;
  PyObject *__pyx_v_c;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  Py_ssize_t __pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  __pyx_v_e = Py_None; Py_INCREF(Py_None);
  __pyx_v_v = Py_None; Py_INCREF(Py_None);
  __pyx_v_c = Py_None; Py_INCREF(Py_None);

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":91
 *             
 *     def tick(self):
 *         if self.child_need_resize:             # <<<<<<<<<<<<<< 
 *             self.do_resize()
 *             self.child_need_resize = False
 */
  __pyx_1 = ((struct __pyx_obj_6window_Window *)__pyx_v_self)->child_need_resize;
  if (__pyx_1) {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":92
 *     def tick(self):
 *         if self.child_need_resize:
 *             self.do_resize()             # <<<<<<<<<<<<<< 
 *             self.child_need_resize = False
 *         if self.child_need_organize:
 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_do_resize); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":93
 *         if self.child_need_resize:
 *             self.do_resize()
 *             self.child_need_resize = False             # <<<<<<<<<<<<<< 
 *         if self.child_need_organize:
 *             self.do_organize()
 */
    ((struct __pyx_obj_6window_Window *)__pyx_v_self)->child_need_resize = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":94
 *             self.do_resize()
 *             self.child_need_resize = False
 *         if self.child_need_organize:             # <<<<<<<<<<<<<< 
 *             self.do_organize()
 *             self.child_need_organize = False
 */
  __pyx_1 = ((struct __pyx_obj_6window_Window *)__pyx_v_self)->child_need_organize;
  if (__pyx_1) {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":95
 *             self.child_need_resize = False
 *         if self.child_need_organize:
 *             self.do_organize()             # <<<<<<<<<<<<<< 
 *             self.child_need_organize = False
 *         
 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_do_organize); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":96
 *         if self.child_need_organize:
 *             self.do_organize()
 *             self.child_need_organize = False             # <<<<<<<<<<<<<< 
 *         
 *         self.events = []
 */
    ((struct __pyx_obj_6window_Window *)__pyx_v_self)->child_need_organize = 0;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":98
 *             self.child_need_organize = False
 *         
 *         self.events = []             # <<<<<<<<<<<<<< 
 *         if self.modal_child is None:
 *             for e,v in self.events_source.events:
 */
  __pyx_2 = PyList_New(0); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->events));
  ((struct __pyx_obj_6window_Window *)__pyx_v_self)->events = __pyx_2;
  __pyx_2 = 0;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":99
 *         
 *         self.events = []
 *         if self.modal_child is None:             # <<<<<<<<<<<<<< 
 *             for e,v in self.events_source.events:
 *                 if e == 'mouse-down':
 */
  __pyx_4 = (((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child) == Py_None);
  if (__pyx_4) {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":100
 *         self.events = []
 *         if self.modal_child is None:
 *             for e,v in self.events_source.events:             # <<<<<<<<<<<<<< 
 *                 if e == 'mouse-down':
 *                     if self.mouse_down(v[0]): continue
 */
    __pyx_3 = PyObject_GetAttr(((struct __pyx_obj_6window_Window *)__pyx_v_self)->events_source, __pyx_n_events); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1;}
    if (PyList_CheckExact(__pyx_3)) { __pyx_5 = 0; __pyx_2 = __pyx_3; Py_INCREF(__pyx_2); }
    else { __pyx_2 = PyObject_GetIter(__pyx_3); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1;} }
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    for (;;) {
      if (PyList_CheckExact(__pyx_2)) { if (__pyx_5 >= PyList_GET_SIZE(__pyx_2)) break; __pyx_3 = PyList_GET_ITEM(__pyx_2, __pyx_5++); Py_INCREF(__pyx_3); }
      else {
        __pyx_3 = PyIter_Next(__pyx_2);
        if (!__pyx_3) {
          break;
        }
      }
      if (PyTuple_CheckExact(__pyx_3) && PyTuple_GET_SIZE(__pyx_3) == 2) {
        PyObject* tuple = __pyx_3;
        __pyx_7 = PyTuple_GET_ITEM(tuple, 0);
        Py_INCREF(__pyx_7);
        Py_DECREF(__pyx_v_e);
        __pyx_v_e = __pyx_7;
        __pyx_7 = 0;
        __pyx_7 = PyTuple_GET_ITEM(tuple, 1);
        Py_INCREF(__pyx_7);
        Py_DECREF(__pyx_v_v);
        __pyx_v_v = __pyx_7;
        __pyx_7 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
      }
      else {
        __pyx_6 = PyObject_GetIter(__pyx_3); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        __pyx_7 = __Pyx_UnpackItem(__pyx_6, 0); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_v_e);
        __pyx_v_e = __pyx_7;
        __pyx_7 = 0;
        __pyx_7 = __Pyx_UnpackItem(__pyx_6, 1); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_v_v);
        __pyx_v_v = __pyx_7;
        __pyx_7 = 0;
        if (__Pyx_EndUnpack(__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_6); __pyx_6 = 0;
      }

      /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":101
 *         if self.modal_child is None:
 *             for e,v in self.events_source.events:
 *                 if e == 'mouse-down':             # <<<<<<<<<<<<<< 
 *                     if self.mouse_down(v[0]): continue
 *                 if e == 'mouse-up':
 */
      __pyx_7 = PyObject_RichCompare(__pyx_v_e, __pyx_k_1p, Py_EQ); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_7); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      if (__pyx_4) {

        /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":102
 *             for e,v in self.events_source.events:
 *                 if e == 'mouse-down':
 *                     if self.mouse_down(v[0]): continue             # <<<<<<<<<<<<<< 
 *                 if e == 'mouse-up':
 *                     if self.mouse_up(v[0]): continue
 */
        __pyx_3 = PyObject_GetAttr(__pyx_v_self, __pyx_n_mouse_down); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1;}
        if (PyList_CheckExact(__pyx_v_v) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_v)) {
          __pyx_7 = PyList_GET_ITEM(__pyx_v_v, 0); Py_INCREF(__pyx_7);
          } else if (PyTuple_CheckExact(__pyx_v_v) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_v)) {
          __pyx_7 = PyTuple_GET_ITEM(__pyx_v_v, 0); Py_INCREF(__pyx_7);
          } else {
          __pyx_6 = PyInt_FromLong(0); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1;}
          __pyx_7 = PyObject_GetItem(__pyx_v_v, __pyx_6); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1;}
          Py_DECREF(__pyx_6); __pyx_6 = 0;
        }
        __pyx_6 = PyTuple_New(1); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_6, 0, __pyx_7);
        __pyx_7 = 0;
        __pyx_7 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_6), NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(((PyObject *)__pyx_6)); __pyx_6 = 0;
        __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_7); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        if (__pyx_4) {
          goto __pyx_L7;
          goto __pyx_L10;
        }
        __pyx_L10:;
        goto __pyx_L9;
      }
      __pyx_L9:;

      /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":103
 *                 if e == 'mouse-down':
 *                     if self.mouse_down(v[0]): continue
 *                 if e == 'mouse-up':             # <<<<<<<<<<<<<< 
 *                     if self.mouse_up(v[0]): continue
 *                 if e == 'mouse-motion':
 */
      __pyx_3 = PyObject_RichCompare(__pyx_v_e, __pyx_k_2p, Py_EQ); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_3); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      if (__pyx_4) {

        /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":104
 *                     if self.mouse_down(v[0]): continue
 *                 if e == 'mouse-up':
 *                     if self.mouse_up(v[0]): continue             # <<<<<<<<<<<<<< 
 *                 if e == 'mouse-motion':
 *                     if self.mouse_motion(v[0]): continue
 */
        __pyx_6 = PyObject_GetAttr(__pyx_v_self, __pyx_n_mouse_up); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; __pyx_clineno = __LINE__; goto __pyx_L1;}
        if (PyList_CheckExact(__pyx_v_v) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_v)) {
          __pyx_3 = PyList_GET_ITEM(__pyx_v_v, 0); Py_INCREF(__pyx_3);
          } else if (PyTuple_CheckExact(__pyx_v_v) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_v)) {
          __pyx_3 = PyTuple_GET_ITEM(__pyx_v_v, 0); Py_INCREF(__pyx_3);
          } else {
          __pyx_7 = PyInt_FromLong(0); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; __pyx_clineno = __LINE__; goto __pyx_L1;}
          __pyx_3 = PyObject_GetItem(__pyx_v_v, __pyx_7); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; __pyx_clineno = __LINE__; goto __pyx_L1;}
          Py_DECREF(__pyx_7); __pyx_7 = 0;
        }
        __pyx_7 = PyTuple_New(1); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; __pyx_clineno = __LINE__; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_7, 0, __pyx_3);
        __pyx_3 = 0;
        __pyx_3 = PyObject_Call(__pyx_6, ((PyObject *)__pyx_7), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        Py_DECREF(((PyObject *)__pyx_7)); __pyx_7 = 0;
        __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_3); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        if (__pyx_4) {
          goto __pyx_L7;
          goto __pyx_L12;
        }
        __pyx_L12:;
        goto __pyx_L11;
      }
      __pyx_L11:;

      /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":105
 *                 if e == 'mouse-up':
 *                     if self.mouse_up(v[0]): continue
 *                 if e == 'mouse-motion':             # <<<<<<<<<<<<<< 
 *                     if self.mouse_motion(v[0]): continue
 *                 if e == 'key-down':
 */
      __pyx_6 = PyObject_RichCompare(__pyx_v_e, __pyx_k_3p, Py_EQ); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_6); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      if (__pyx_4) {

        /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":106
 *                     if self.mouse_up(v[0]): continue
 *                 if e == 'mouse-motion':
 *                     if self.mouse_motion(v[0]): continue             # <<<<<<<<<<<<<< 
 *                 if e == 'key-down':
 *                     if self.key_down(*v): continue
 */
        __pyx_7 = PyObject_GetAttr(__pyx_v_self, __pyx_n_mouse_motion); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1;}
        if (PyList_CheckExact(__pyx_v_v) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_v)) {
          __pyx_6 = PyList_GET_ITEM(__pyx_v_v, 0); Py_INCREF(__pyx_6);
          } else if (PyTuple_CheckExact(__pyx_v_v) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_v)) {
          __pyx_6 = PyTuple_GET_ITEM(__pyx_v_v, 0); Py_INCREF(__pyx_6);
          } else {
          __pyx_3 = PyInt_FromLong(0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1;}
          __pyx_6 = PyObject_GetItem(__pyx_v_v, __pyx_3); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1;}
          Py_DECREF(__pyx_3); __pyx_3 = 0;
        }
        __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_3, 0, __pyx_6);
        __pyx_6 = 0;
        __pyx_6 = PyObject_Call(__pyx_7, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
        __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_6); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        if (__pyx_4) {
          goto __pyx_L7;
          goto __pyx_L14;
        }
        __pyx_L14:;
        goto __pyx_L13;
      }
      __pyx_L13:;

      /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":107
 *                 if e == 'mouse-motion':
 *                     if self.mouse_motion(v[0]): continue
 *                 if e == 'key-down':             # <<<<<<<<<<<<<< 
 *                     if self.key_down(*v): continue
 *                 if e == 'resized':
 */
      __pyx_7 = PyObject_RichCompare(__pyx_v_e, __pyx_k_4p, Py_EQ); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_7); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      if (__pyx_4) {

        /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":108
 *                     if self.mouse_motion(v[0]): continue
 *                 if e == 'key-down':
 *                     if self.key_down(*v): continue             # <<<<<<<<<<<<<< 
 *                 if e == 'resized':
 *                     self.size = v[0]
 */
        __pyx_3 = PyObject_GetAttr(__pyx_v_self, __pyx_n_key_down); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1;}
        __pyx_6 = PySequence_Tuple(__pyx_v_v); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1;}
        __pyx_7 = PyObject_Call(__pyx_3, __pyx_6, NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_7); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        if (__pyx_4) {
          goto __pyx_L7;
          goto __pyx_L16;
        }
        __pyx_L16:;
        goto __pyx_L15;
      }
      __pyx_L15:;

      /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":109
 *                 if e == 'key-down':
 *                     if self.key_down(*v): continue
 *                 if e == 'resized':             # <<<<<<<<<<<<<< 
 *                     self.size = v[0]
 *                     self.resized = False
 */
      __pyx_3 = PyObject_RichCompare(__pyx_v_e, __pyx_n_resized, Py_EQ); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_3); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      if (__pyx_4) {

        /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":110
 *                     if self.key_down(*v): continue
 *                 if e == 'resized':
 *                     self.size = v[0]             # <<<<<<<<<<<<<< 
 *                     self.resized = False
 *                     continue
 */
        if (PyList_CheckExact(__pyx_v_v) && 0 <= 0 && 0 < PyList_GET_SIZE(__pyx_v_v)) {
          __pyx_7 = PyList_GET_ITEM(__pyx_v_v, 0); Py_INCREF(__pyx_7);
          } else if (PyTuple_CheckExact(__pyx_v_v) && 0 <= 0 && 0 < PyTuple_GET_SIZE(__pyx_v_v)) {
          __pyx_7 = PyTuple_GET_ITEM(__pyx_v_v, 0); Py_INCREF(__pyx_7);
          } else {
          __pyx_6 = PyInt_FromLong(0); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L1;}
          __pyx_7 = PyObject_GetItem(__pyx_v_v, __pyx_6); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L1;}
          Py_DECREF(__pyx_6); __pyx_6 = 0;
        }
        if (PyObject_SetAttr(__pyx_v_self, __pyx_n_size, __pyx_7) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L1;}
        Py_DECREF(__pyx_7); __pyx_7 = 0;

        /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":111
 *                 if e == 'resized':
 *                     self.size = v[0]
 *                     self.resized = False             # <<<<<<<<<<<<<< 
 *                     continue
 *             for c in self.children:
 */
        if (PyObject_SetAttr(__pyx_v_self, __pyx_n_resized, Py_False) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; __pyx_clineno = __LINE__; goto __pyx_L1;}

        /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":112
 *                     self.size = v[0]
 *                     self.resized = False
 *                     continue             # <<<<<<<<<<<<<< 
 *             for c in self.children:
 *                 c.tick()
 */
        goto __pyx_L7;
        goto __pyx_L17;
      }
      __pyx_L17:;
      __pyx_L7:;
    }
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":113
 *                     self.resized = False
 *                     continue
 *             for c in self.children:             # <<<<<<<<<<<<<< 
 *                 c.tick()
 *         else:
 */
    if (PyList_CheckExact(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->__pyx_base.children))) { __pyx_5 = 0; __pyx_3 = ((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->__pyx_base.children); Py_INCREF(__pyx_3); }
    else { __pyx_3 = PyObject_GetIter(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->__pyx_base.children)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; __pyx_clineno = __LINE__; goto __pyx_L1;} }
    for (;;) {
      if (PyList_CheckExact(__pyx_3)) { if (__pyx_5 >= PyList_GET_SIZE(__pyx_3)) break; __pyx_6 = PyList_GET_ITEM(__pyx_3, __pyx_5++); Py_INCREF(__pyx_6); }
      else {
        __pyx_6 = PyIter_Next(__pyx_3);
        if (!__pyx_6) {
          break;
        }
      }
      Py_DECREF(__pyx_v_c);
      __pyx_v_c = __pyx_6;
      __pyx_6 = 0;

      /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":114
 *                     continue
 *             for c in self.children:
 *                 c.tick()             # <<<<<<<<<<<<<< 
 *         else:
 *             self.events = self.events_source.events
 */
      __pyx_7 = PyObject_GetAttr(__pyx_v_c, __pyx_n_tick); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; __pyx_clineno = __LINE__; goto __pyx_L1;}
      __pyx_2 = PyObject_Call(__pyx_7, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; __pyx_clineno = __LINE__; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
    }
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L6;
  }
  /*else*/ {

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":116
 *                 c.tick()
 *         else:
 *             self.events = self.events_source.events             # <<<<<<<<<<<<<< 
 *             self.modal_child.tick()
 *         self._emit('tick')
 */
    __pyx_6 = PyObject_GetAttr(((struct __pyx_obj_6window_Window *)__pyx_v_self)->events_source, __pyx_n_events); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; __pyx_clineno = __LINE__; goto __pyx_L1;}
    if (!(likely(PyList_CheckExact(__pyx_6)) || (__pyx_6) == Py_None || (PyErr_Format(PyExc_TypeError, "Expected list, got %s", __pyx_6->ob_type->tp_name), 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->events));
    ((struct __pyx_obj_6window_Window *)__pyx_v_self)->events = ((PyObject *)__pyx_6);
    __pyx_6 = 0;

    /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":117
 *         else:
 *             self.events = self.events_source.events
 *             self.modal_child.tick()             # <<<<<<<<<<<<<< 
 *         self._emit('tick')
 */
    __pyx_7 = PyObject_GetAttr(((PyObject *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->modal_child), __pyx_n_tick); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_2 = PyObject_Call(__pyx_7, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }
  __pyx_L6:;

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":118
 *             self.events = self.events_source.events
 *             self.modal_child.tick()
 *         self._emit('tick')             # <<<<<<<<<<<<<< 
 */
  ((struct __pyx_vtabstruct_6window_Window *)((struct __pyx_obj_6window_Window *)__pyx_v_self)->__pyx_base.__pyx_base.__pyx_vtab)->__pyx_base.__pyx_base._emit(((struct __pyx_obj_7cobject_Object *)__pyx_v_self), __pyx_k_6); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("window.Window.tick");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_v);
  Py_DECREF(__pyx_v_c);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n_do_organize, "do_organize"},
  {&__pyx_n_do_resize, "do_resize"},
  {&__pyx_n_events, "events"},
  {&__pyx_n_key_down, "key_down"},
  {&__pyx_n_mouse_down, "mouse_down"},
  {&__pyx_n_mouse_motion, "mouse_motion"},
  {&__pyx_n_mouse_up, "mouse_up"},
  {&__pyx_n_need_organize, "need_organize"},
  {&__pyx_n_need_resize, "need_resize"},
  {&__pyx_n_remove, "remove"},
  {&__pyx_n_resize, "resize"},
  {&__pyx_n_resized, "resized"},
  {&__pyx_n_reversed, "reversed"},
  {&__pyx_n_size, "size"},
  {&__pyx_n_sorted_children, "sorted_children"},
  {&__pyx_n_super, "super"},
  {&__pyx_n_tick, "tick"},
  {&__pyx_n_window, "window"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k_1p, __pyx_k_1, sizeof(__pyx_k_1), 0},
  {&__pyx_k_2p, __pyx_k_2, sizeof(__pyx_k_2), 0},
  {&__pyx_k_3p, __pyx_k_3, sizeof(__pyx_k_3), 0},
  {&__pyx_k_4p, __pyx_k_4, sizeof(__pyx_k_4), 0},
  {0, 0, 0, 0}
};
static struct __pyx_vtabstruct_6window_Window __pyx_vtable_6window_Window;

static PyObject *__pyx_tp_new_6window_Window(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_6window_Window *p;
  PyObject *o = __pyx_ptype_6widget_Widget->tp_new(t, a, k);
  if (!o) return 0;
  p = ((struct __pyx_obj_6window_Window *)o);
  *(struct __pyx_vtabstruct_6window_Window **)&p->__pyx_base.__pyx_base.__pyx_vtab = __pyx_vtabptr_6window_Window;
  p->events = ((PyObject *)Py_None); Py_INCREF(Py_None);
  p->events_source = Py_None; Py_INCREF(Py_None);
  p->modal_child = ((struct __pyx_obj_6window_Window *)Py_None); Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_6window_Window(PyObject *o) {
  struct __pyx_obj_6window_Window *p = (struct __pyx_obj_6window_Window *)o;
  Py_XDECREF(((PyObject *)p->events));
  Py_XDECREF(p->events_source);
  Py_XDECREF(((PyObject *)p->modal_child));
  __pyx_ptype_6widget_Widget->tp_dealloc(o);
}

static int __pyx_tp_traverse_6window_Window(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_6window_Window *p = (struct __pyx_obj_6window_Window *)o;
  if (__pyx_ptype_6widget_Widget->tp_traverse) {
    e = __pyx_ptype_6widget_Widget->tp_traverse(o, v, a); if (e) return e;
  }
  if (p->events) {
    e = (*v)(p->events, a); if (e) return e;
  }
  if (p->events_source) {
    e = (*v)(p->events_source, a); if (e) return e;
  }
  if (p->modal_child) {
    e = (*v)(((PyObject*)p->modal_child), a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_6window_Window(PyObject *o) {
  struct __pyx_obj_6window_Window *p = (struct __pyx_obj_6window_Window *)o;
  PyObject* tmp;
  if (__pyx_ptype_6widget_Widget->tp_clear) {
    __pyx_ptype_6widget_Widget->tp_clear(o);
  }
  tmp = ((PyObject*)p->events);
  p->events = ((PyObject *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(tmp);
  tmp = ((PyObject*)p->events_source);
  p->events_source = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(tmp);
  tmp = ((PyObject*)p->modal_child);
  p->modal_child = ((struct __pyx_obj_6window_Window *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(tmp);
  return 0;
}

static struct PyMethodDef __pyx_methods_6window_Window[] = {
  {"remove", (PyCFunction)__pyx_pf_6window_6Window_remove, METH_O, 0},
  {"resize", (PyCFunction)__pyx_pf_6window_6Window_resize, METH_NOARGS, 0},
  {"sorted_children", (PyCFunction)__pyx_pf_6window_6Window_sorted_children, METH_NOARGS, 0},
  {"need_organize", (PyCFunction)__pyx_pf_6window_6Window_need_organize, METH_O, 0},
  {"need_resize", (PyCFunction)__pyx_pf_6window_6Window_need_resize, METH_O, 0},
  {"tick", (PyCFunction)__pyx_pf_6window_6Window_tick, METH_NOARGS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_6window_Window[] = {
  {"events", T_OBJECT, offsetof(struct __pyx_obj_6window_Window, events), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Window = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Window = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Window = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Window = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_6window_Window = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "window.Window", /*tp_name*/
  sizeof(struct __pyx_obj_6window_Window), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_6window_Window, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Window, /*tp_as_number*/
  &__pyx_tp_as_sequence_Window, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Window, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Window, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  " Special widget that can receive events from an external source\n        \n        A window can also be an event source for other sub window. We can also block the events to all but one\n        child, making it a modal dialog.\n    ", /*tp_doc*/
  __pyx_tp_traverse_6window_Window, /*tp_traverse*/
  __pyx_tp_clear_6window_Window, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_6window_Window, /*tp_methods*/
  __pyx_members_6window_Window, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_6window_6Window___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_6window_Window, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initwindow(void); /*proto*/
PyMODINIT_FUNC initwindow(void) {
  PyObject *__pyx_1 = 0;
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("window", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_builtin_super = __Pyx_GetName(__pyx_b, __pyx_n_super); if (!__pyx_builtin_super) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_builtin_reversed = __Pyx_GetName(__pyx_b, __pyx_n_reversed); if (!__pyx_builtin_reversed) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_ptype_6widget_Widget = __Pyx_ImportType("widget", "Widget", sizeof(struct __pyx_obj_6widget_Widget)); if (unlikely(!__pyx_ptype_6widget_Widget)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_6widget_Widget->tp_dict, &__pyx_vtabptr_6widget_Widget) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_vtabptr_6window_Window = &__pyx_vtable_6window_Window;
  __pyx_vtable_6window_Window.__pyx_base = *__pyx_vtabptr_6widget_Widget;
  *(void(**)(void))&__pyx_vtable_6window_Window.__pyx_base.c_draw = (void(*)(void))__pyx_f_6window_6Window_c_draw;
  __pyx_type_6window_Window.tp_base = __pyx_ptype_6widget_Widget;
  if (PyType_Ready(&__pyx_type_6window_Window) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_6window_Window.tp_dict, __pyx_vtabptr_6window_Window) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Window", (PyObject *)&__pyx_type_6window_Window) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6window_Window = &__pyx_type_6window_Window;
  /*--- Type import code ---*/
  __pyx_ptype_3geo_Vect = __Pyx_ImportType("geo", "Vect", sizeof(struct __pyx_obj_3geo_Vect)); if (unlikely(!__pyx_ptype_3geo_Vect)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_3geo_Rect = __Pyx_ImportType("geo", "Rect", sizeof(struct __pyx_obj_3geo_Rect)); if (unlikely(!__pyx_ptype_3geo_Rect)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_3geo_Rect->tp_dict, &__pyx_vtabptr_3geo_Rect) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_7cobject_Object = __Pyx_ImportType("cobject", "Object", sizeof(struct __pyx_obj_7cobject_Object)); if (unlikely(!__pyx_ptype_7cobject_Object)) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_7cobject_Object->tp_dict, &__pyx_vtabptr_7cobject_Object) < 0) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_7painter_Painter = __Pyx_ImportType("painter", "Painter", sizeof(struct __pyx_obj_7painter_Painter)); if (unlikely(!__pyx_ptype_7painter_Painter)) {__pyx_filename = __pyx_f[3]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_GetVtable(__pyx_ptype_7painter_Painter->tp_dict, &__pyx_vtabptr_7painter_Painter) < 0) {__pyx_filename = __pyx_f[3]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1;}
  /*--- Function import code ---*/
  __pyx_1 = __Pyx_ImportModule("geo"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_vect_to_py", (void**)&__pyx_f_3geo_c_vect_to_py, "struct __pyx_obj_3geo_Vect *(struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_vect_equal", (void**)&__pyx_f_3geo_c_vect_equal, "int (struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_to_py", (void**)&__pyx_f_3geo_c_rect_to_py, "struct __pyx_obj_3geo_Rect *(struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_left", (void**)&__pyx_f_3geo_c_rect_left, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_right", (void**)&__pyx_f_3geo_c_rect_right, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_top", (void**)&__pyx_f_3geo_c_rect_top, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_bottom", (void**)&__pyx_f_3geo_c_rect_bottom, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_width", (void**)&__pyx_f_3geo_c_rect_width, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_height", (void**)&__pyx_f_3geo_c_rect_height, "int (struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_contains", (void**)&__pyx_f_3geo_c_rect_contains, "int (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_intersect", (void**)&__pyx_f_3geo_c_rect_intersect, "int (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_inside", (void**)&__pyx_f_3geo_c_rect_inside, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_merge", (void**)&__pyx_f_3geo_c_rect_merge, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_clip", (void**)&__pyx_f_3geo_c_rect_clip, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_ImportFunction(__pyx_1, "c_rect_move", (void**)&__pyx_f_3geo_c_rect_move, "void (struct __pyx_t_3geo_c_Rect *, struct __pyx_t_3geo_c_Vect *, struct __pyx_t_3geo_c_Rect *)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  /*--- Execution code ---*/

  /* "/home/charlie/Work/tichy/tichy/guic/window.pyx":90
 *         self.child_need_resize = True
 *             
 *     def tick(self):             # <<<<<<<<<<<<<< 
 *         if self.child_need_resize:
 *             self.do_resize()
 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("window");
}

static char *__pyx_filenames[] = {
  "window.pyx",
  "geo.pxd",
  "cobject.pxd",
  "painter.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name, int exact) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (none_allowed && obj == Py_None) return 1;
    else if (exact) {
        if (obj->ob_type == type) return 1;
    }
    else {
        if (PyObject_TypeCheck(obj, type)) return 1;
    }
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static int __Pyx_SplitKeywords(
    PyObject **kwds,
    char *kwd_list[], 
    PyObject **kwds2,
    char rqd_kwds[])
{
    PyObject *s = 0, *x = 0, *kwds1 = 0;
    int i;
    char **p;
    
    if (*kwds) {
        kwds1 = PyDict_New();
        if (!kwds1)
            goto bad;
        *kwds2 = PyDict_Copy(*kwds);
        if (!*kwds2)
            goto bad;
        for (i = 0, p = kwd_list; *p; i++, p++) {
            s = PyString_FromString(*p);
            x = PyDict_GetItem(*kwds, s);
            if (x) {
                if (PyDict_SetItem(kwds1, s, x) < 0)
                    goto bad;
                if (PyDict_DelItem(*kwds2, s) < 0)
                    goto bad;
            }
            else if (rqd_kwds && rqd_kwds[i])
                goto missing_kwarg;
            Py_DECREF(s);
        }
        s = 0;
    }
    else {
        if (rqd_kwds) {
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i])
                    goto missing_kwarg;
        }
        *kwds2 = PyDict_New();
        if (!*kwds2)
            goto bad;
    }

    *kwds = kwds1;
    return 0;
missing_kwarg:
    PyErr_Format(PyExc_TypeError,
        "required keyword argument '%s' is missing", *p);
bad:
    Py_XDECREF(s);
    Py_XDECREF(kwds1);
    Py_XDECREF(*kwds2);
    return -1;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_UnpackItem(PyObject *iter, Py_ssize_t index) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred()) {
            PyErr_Format(PyExc_ValueError,
                #if PY_VERSION_HEX < 0x02050000
                    "need more than %d values to unpack", (int)index);
                #else
                    "need more than %zd values to unpack", index);
                #endif
        }
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        PyErr_SetString(PyExc_ValueError, "too many values to unpack");
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;
    
    py_name = PyString_FromString(module_name);
    if (!py_name)
        goto bad;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_name);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;
    
    py_name = PyString_FromString(name);
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr) {
    int result;
    PyObject *pycobj;
    
    pycobj = PyMapping_GetItemString(dict, "__pyx_vtable__");
    if (!pycobj)
        goto bad;
    *(void **)vtabptr = PyCObject_AsVoidPtr(pycobj);
    if (!*(void **)vtabptr)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    char *desc;
    
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%s does not export expected C function %s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    desc = (char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    if (strcmp(desc, sig) != 0) {
        PyErr_Format(PyExc_TypeError,
            "C function %s.%s has wrong signature (expected %s, got %s)",
                PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    *f = PyCObject_AsVoidPtr(cobj);
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
    }
    else {
        py_funcname = PyString_FromString(funcname);
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
